examples/generate-examples.sh

Buildkite is now running in a different namespace. It seems helm by default
uses the current namespace, which I assume it gets from the default service
account. As such this was leading to CI failing since the example templates
would have the NS set to "buildkite".

ci: Specify namespace in generate-examples

---

examples/aws/generated/sourcegraph/templates/indexed-search/indexed-search.Deployment.yaml
examples/gcp/generated/sourcegraph/templates/indexed-search/indexed-search.Deployment.yaml
examples/manual-storage-class/generated/sourcegraph/templates/indexed-search/indexed-search.Deployment.yaml
examples/node-selector/generated/sourcegraph/templates/indexed-search/indexed-search.Deployment.yaml
examples/prometheus/generated/sourcegraph/templates/indexed-search/indexed-search.Deployment.yaml
examples/with-langs/generated/sourcegraph/templates/indexed-search/indexed-search.Deployment.yaml
templates/indexed-search/indexed-search.Deployment.yaml
values.yaml

We also bump the container to use to include the migration.
Part of https://github.com/sourcegraph/sourcegraph/issues/10775

indexed-search: Add migration env var

---

templates/lsp-proxy/lsp-proxy.Deployment.yaml
templates/xlang/experimental.yaml
values.yaml

This uses templating functions to range over the `langservers` in the site configuration. That means that all the user has to do is add entries to `langservers` (e.g. `{ "language": "rust" }`) and the Data Center installation will be spun up with the corresponding container.
TODO

Add experimental language servers

---

examples/with-langs/generated/sourcegraph/templates/xlang/go/xlang-go-bg.Deployment.yaml
examples/with-langs/generated/sourcegraph/templates/xlang/go/xlang-go.Deployment.yaml
values.yaml

This updates the xlang-go image version to include a fix for the Go
language server returning poor error messages `invalid location` for
unsupported CGO files rather than a more legible `File $FILE is ignored by the build.`
error.
See https://github.com/sourcegraph/issues/issues/59

update xlang-go image version

---

examples/aws/generated/sourcegraph/templates/lsp-proxy/lsp-proxy.Deployment.yaml
examples/gcp/generated/sourcegraph/templates/lsp-proxy/lsp-proxy.Deployment.yaml
examples/manual-storage-class/generated/sourcegraph/templates/lsp-proxy/lsp-proxy.Deployment.yaml
examples/node-selector/generated/sourcegraph/templates/lsp-proxy/lsp-proxy.Deployment.yaml
examples/prometheus/generated/sourcegraph/templates/lsp-proxy/lsp-proxy.Deployment.yaml
examples/with-exp-langs/generated/sourcegraph/templates/lsp-proxy/lsp-proxy.Deployment.yaml
examples/with-langs/generated/sourcegraph/templates/lsp-proxy/lsp-proxy.Deployment.yaml
values.yaml

This new version of lsp-proxy includes an increase to the amount of time that lsp-proxy will wait for a language server to initialize before timing out the request, and a better error message for when the timeout occurs.

bump lsp-proxy version tag

---

templates/lsp-proxy/lsp-proxy.Deployment.yaml

Previously, setting `langservers.address` had no effect because your setting would be ignored by the helm templating logic (my fault 😞 ).
This fixes the logic so that your address is respected.
@beyang This is a requirement for merging in the config changes for experimental language servers into https://github.com/sourcegraph/infrastructure Once this is merged in, do we need to tag the commit for a release so that this fix gets picked up by https://github.com/sourcegraph/infrastructure ?

Respect the langservers.address field

---

examples/aws/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/aws/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/custom-env-vars/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/custom-env-vars/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/gcp/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/gcp/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/manual-storage-class/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/manual-storage-class/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/node-selector/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/node-selector/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/prometheus/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/prometheus/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/with-exp-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/with-exp-langs/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/with-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/with-langs/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
test-cases/custom-ls-address/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
test-cases/custom-ls-address/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
values.yaml

This updates the syntect_server version to the latest which includes lots of goodies. Additionally, in order to do so, we must bump the frontend version to at least this version.
I will merge right now so this will be in the next release.
Note: The frontend is backwards-compatible with the old syntect_server version for now, but frontend versions older than the one specified here are not forwards-compatible with the new syntect_server version.

release new syntect_server version + bump frontend version

---

examples/aws/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/custom-env-vars/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/gcp/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/manual-storage-class/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/node-selector/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/prometheus/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/with-exp-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/with-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
templates/_helpers.tpl
test-cases/custom-ls-address/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
test-cases/with-jaeger/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml

The default value is `http://query-runner` in the code.
Related to https://github.com/sourcegraph/infrastructure/pull/604

remove QUERY_RUNNER_URL

---

examples/aws/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/custom-env-vars/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/gcp/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/manual-storage-class/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/node-selector/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/prometheus/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/with-exp-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/with-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
templates/_helpers.tpl
test-cases/custom-ls-address/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
test-cases/with-jaeger/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml

Rely on default behavior in the code.
See https://github.com/sourcegraph/infrastructure/pull/607

remove REPO_UPDATER_URL

---

examples/aws/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/custom-env-vars/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/gcp/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/manual-storage-class/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/node-selector/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/prometheus/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/with-exp-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
examples/with-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
templates/frontend/sourcegraph-frontend.Deployment.yaml
test-cases/custom-ls-address/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
test-cases/with-jaeger/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
values.yaml

remove ZOEKT_HOST and rely on default behavior

---

examples/aws/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/custom-env-vars/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/gcp/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/manual-storage-class/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/node-selector/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/prometheus/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/with-exp-langs/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
examples/with-langs/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
test-cases/custom-ls-address/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
test-cases/with-jaeger/generated/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
update_docker_image_versions.py
values.yaml

The commit https://github.com/sourcegraph/deploy-sourcegraph/commit/b74e58681aeb4188df62ae6ce4932b50567664ce updated the syntect_server version using the new `update_docker_image_versions.py` script. However, our dogfood instance does not have automatic deployments of syntect_server (it is special in this regard), and hence using the version from there is incorrect as it can be outdated.
The syntect_server version is now hard-coded in `update_docker_image_versions.py`, and the `values.yaml` file has been manually adjusted to use the latest `syntect_server` version once again (done manually to avoid updating other image versions for a patch release).
This fixes a regression where e.g. Java files would be improperly highlighted. See internal issue: sourcegraph/sourcegraph#12537

correct the outdated syntect_server version

---

examples/custom-env-vars/generated/sourcegraph/templates/prometheus/alertmanager/alertmanager.Deployment.yaml
templates/prometheus/alertmanager/alertmanager.Deployment.yaml
test-cases/with-jaeger/generated/sourcegraph/templates/prometheus/alertmanager/alertmanager.Deployment.yaml
values.yaml

The version we are using is ancient. For example the old version used a deprecated opsgenie API.

Upgrade alertmanager to v0.15.1

---

docs/configure.md

This PR adds the `GS` variable's definition (which was missing before), and remove the quotes around `replicas: n` that the old script would insert.

fix gitserver replica count script

---

base/frontend/sourcegraph-frontend.Deployment.yaml

@keegancsmith spent time debugging https://github.com/sourcegraph/sourcegraph/issues/11253 and found out that ultimately, searches with tons of results causes an OOM in frontend. We implemented https://github.com/sourcegraph/sourcegraph/commit/c89f07406e4461726a04a0b783d023985d8d9803 to limit the number of results Zoekt would return since it wasn't following the limits the user would set in `max`, but this doesn't solve the reproducible case in the issue. Ultimately, to solve it, we would need to bump the CPU resources in frontend.

Double CPU resources for frontend

---

docs/configure.md
docs/k8s.eks.md
docs/k8s.md

- This PR adds documentation for how to deploy Sourcegraph on Amazon EKS.
- We now recommend EKS over raw/plain AWS EC2 (managing your own Kubernetes cluster) as it is better in general for this.
- Note: At first glance when reviewing this, the documentation may look as though it repeats a lot of information found in EKS docs, and this is true. The EKS docs (all AWS docs) are very verbose which is great for finding obscure information sometimes, but awful for getting started.
- The k8s.eks.md file is essentially a distillation of the official EKS documentation, reducing and clarifying the amount of documentation you must read/follow by about 6-8 pages roughly.

docs: add Amazon EKS deployment documentation

---

docs/configure.md

When I was going through these install instructions, I missed the `provisioner` field the first time because I was just copy-pasting the snippets. Any reason not to include these?

include `provisioner` field in docs

---

docs/configure.md

- The link to the k8s documentation needed to be updated for GCP (the header on the website has changed since this section was written
- Added a warning about using the `replication-type` field for pre `1.10` Kubernetes versions with gcp

fix gcp instructions for setting up the storage class

---

configure/xlang/experimental/bash/README.md
configure/xlang/experimental/clojure/README.md
configure/xlang/experimental/cpp/README.md
configure/xlang/experimental/cs/README.md
configure/xlang/experimental/css/README.md
configure/xlang/experimental/dockerfile/README.md
configure/xlang/experimental/elixir/README.md
configure/xlang/experimental/html/README.md
configure/xlang/experimental/lua/README.md
configure/xlang/experimental/ocaml/README.md
configure/xlang/experimental/r/README.md
configure/xlang/experimental/ruby/README.md
configure/xlang/experimental/rust/README.md
configure/xlang/go/README.md
configure/xlang/java/README.md
configure/xlang/php/README.md
configure/xlang/python/README.md
configure/xlang/typescript/README.md

This drops the `LANGSERVER_*` environment variables (except the ones ending in `_BG`) in favor of adding entries to the `langservers` array in site config because the Sourcegraph extension corresponding to a language server will not be enabled unless there is an entry for it in the `langservers` array in site config.
The `LANGSERVER_*` environment variables will enable the language server, but not the corresponding Sourcegraph extension.
cc @chrismwendt

xlang: add instruction in docs to add entry to site configuration when you enable a language server

---

docs/install.md

The default appURL is localhost:3080 and now that `canonicalURLRedirect` defaults to true these instructions didn't work because the local port needs to be 3080 instead of 30080.

Fix verification instructions

---

base/frontend/sourcegraph-frontend.Deployment.yaml

Somewhere between 2.12.3 and 2.13.0 the frontend healthcheck started failing. I have not debugged further why yet, but this is a quick fix.

Remove liveness check for sourcegraph-frontend

---

base/management-console/management-console.Deployment.yaml

If `maxUnavailable` is set to 0, then the deployment can never be updated since the old pod will never release its claim on the `management-console` PVC. 
We set `maxUnavailable` to `1` in other stateful services like pgsql:
https://github.com/sourcegraph/deploy-sourcegraph/blob/c01dfc624b8e8072c89e6c9ae4c5404d3368eb64/base/pgsql/pgsql.Deployment.yaml#L16-L20
cc @slimsag

management-console: set max unavailable to 1

---

configure/prometheus/prometheus.ConfigMap.yaml

It isn't expected to perform with the same latency as interactive endpoints.

Exclude raw route from page load latency alert

---

base/redis/redis-store.ConfigMap.yaml
base/redis/redis-store.Deployment.yaml

Fixes: https://github.com/sourcegraph/sourcegraph/issues/1761
This PR reverts the redis-store changes in 45a9fedca3e4031bf5d33a792868f277a13965df, which makes the redis-store deplyoment healthy again.

redis-store: revert pure-docker simplifications

---

configure/ingress-nginx/README.md
configure/ingress-nginx/cloud-generic.yaml
configure/ingress-nginx/mandatory.yaml

https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.22.0 was released a few hours ago. 
@keegancsmith I haven't tested it yet - I just updated the manifests

ingress-nginx: bump to v0.22.0

---

base/gitserver/gitserver.StatefulSet.yaml
base/pgsql/pgsql.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml

gitserver, redis, and pgsql represent single points of failure for a Sourcegraph instance. If those services go down, then your sourcegraph.com will be unavailable / experience major issues. 
By setting `resource.requests=resource.limits` for each container in a pod, [the pod's QoS class is considered "guaranteed"](https://medium.com/google-cloud/quality-of-service-class-qos-in-kubernetes-bb76a89eb2c6), which means that K8s will kill all other services before these pods if the node is resource constrained.

gitserver, postgres, redis: resource requests == resource limits

---

base/frontend/sourcegraph-frontend.Deployment.yaml

Since we added the raw endpoint we have been downloading larger items into our
/tmp dir. This has caused the container to quickly use up node space, leading
to the kubernetes scheduler killing the pod. By specifying CACHE_DIR we can
instead use a different directory with more space.
Part of https://github.com/sourcegraph/sourcegraph/issues/1913

frontend: Add CACHE_DIR env and volume

---

base/pgsql/pgsql.Deployment.yaml

Our pgsql image automatically upgrades from 9.4 to 11.1. However, this can be a
slow process leading to the liveness probe killing the pod before the migration
is finished. Our image now embeds scripts to check the liveness and readiness:
- readiness checks if postgres is available via TCP us pg_isready
- liveness passes if we are upgrading. Otherwise it uses the readiness check.
This should also fix the postgres log spam about bad TCP clients, since we are
removing the dumb TCP probe we used to have.
Part of https://github.com/sourcegraph/sourcegraph/issues/1404

pgsql: Use smarter readiness and liveness probes

---

base/pgsql/pgsql.Deployment.yaml
docs/sourcegraph-3.0.migrate.md

This commit reverts back from the 11.1 Postgres version since we couldn't finish everything in time.
Follow up: https://github.com/sourcegraph/sourcegraph/issues/1404#issuecomment-459900259

Revert Postgres to 9.4 for the 3.0 release

---

renovate.json

This makes testing easier and is ok because our releases are tagged.
https://renovatebot.com/docs/configuration-options/#ignoreunstable

Have renovate automatically update to release candidates

---

base/frontend/sourcegraph-frontend.Deployment.yaml

The frontend requires other services to be running, so it needlessly enters CrashLoopBackoff during normal startup.

Delay frontend liveness check to 5 minutes

---

renovate.json

This tells Renovate to assume semver-compatible versioning for all sourcegraph images. By default Renovate assumes typical Dockerish versions, where the suffix is related to platform (e.g. `3.1.0-alpine` and not semver-like (e.g. `3.1.0-rc.3`).

Use semver versionScheme for sourcegraph images

---

base/frontend/sourcegraph-frontend.Role.yaml
base/frontend/sourcegraph-frontend.RoleBinding.yaml
base/frontend/sourcegraph-frontend.ServiceAccount.yaml
configure/prometheus/prometheus.ClusterRole.yaml
configure/prometheus/prometheus.ClusterRoleBinding.yaml
configure/ssd/pod-tmp-gc.ClusterRole.yaml
configure/ssd/pod-tmp-gc.ClusterRoleBinding.yaml

Deploying [RBAC](https://kubernetes.io/docs/reference/access-authn-authz/rbac/) manifests to a Kubernetes cluster might require elevated permissions (which could be undesirable in some CD scenarios).
This PR adds a `category: rbac` label to all RBAC manifests. This makes it possible to possible [to exclude these manifests](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) from certain `kubectl` operations (e.g `-l deploy=sourcegraph,category!=rbac)

add category:rbac label

---

docs/install.md

We rely on StatefulSets which became GA in 1.9. A customer just experienced an issue when attempting to deploy to a 1.8.7 cluster.
https://sourcegraph.slack.com/archives/C07KZF47K/p1551220913135300

Minimum required k8s version is 1.9

---

base/repo-updater/repo-updater.Deployment.yaml

This commit adds missing pgsql env vars to the repo-updater deployment.
Part of https://github.com/sourcegraph/sourcegraph/issues/2025

repo-updater: Add pgsql env vars

---

base/repo-updater/repo-updater.Deployment.yaml

Since https://github.com/sourcegraph/sourcegraph/pull/3346 repo-updater relies on the ServiceConnections config it fetches from the frontend. Now admins do not need to configure multiple deployments when updating PG settings.
Part of https://github.com/sourcegraph/sourcegraph/issues/2025

Do not specify PG* envvars in repo-updater

---

configure/lang/go/lang-go.Ingress.yaml

The tls secret for lang-go should be separate from the one that you use for `sourcegraph.example.com` since lang-go needs to be deployed under a different hostname.

lang-go: fix default secret-name

---

base/frontend/sourcegraph-frontend.Ingress.yaml
docs/configure.md

In https://github.com/sourcegraph/deploy-sourcegraph/pull/230, I removed the default wildcard handler for sourcegraph-frontend.Ingress.yaml for the following reasons: 
1. Specifying a `host` is required if you're using TLS with an Ingress definition
1. Every customer is probably going to use https
1. Using TLS/SSL for `'sourcegraph.example.com'` (your instance) is required for secure communication with language servers
However, this can lead to confusing behavior when we spin up a test instance of sourcegraph. If you're just connecting to the instance via the load balancer's ip address (and not adding an /etc/hosts entry or provisioning a domain name), those requests won't get forwarded to the `sourcegraph-frontend` service since sourcegraph-frontend.Ingress.yaml is expecting a specific …

add back default host for sourcegraph-frontend ingress

---

configure/lang/go/README.md

This commit changes the documentation for the Go language server
deployment to make it clearer that, you can try out the Go language
server support...
1. ... without having to setup TLS/SSL (even though we recommend it!)
2. ... without having to use HTTP basic authentication (even though we recommend it!)
In order to that, I did three things:
1. add a suffix to the two sections so it's clear you can skip the "Setup
TLS/SSL" and "HTTP Basic authentication" section
2. extract the updating of the global settings into a separate step so
readers won't miss it when they skip HTTP basic auth
3. extend the section about global settings to explain what to do when
the first two sections were skipped

Update documentation for Go language server deployment

---

configure/lang/typescript/README.md

After I merged #244 I noticed that the Typescript docs use the exact same structure, so this PR here  takes the changes made to the Go lang server documentation in PR #244 and adapts them for the Typescript language server

Update documentation for Typescript language server deployment

---

configure/prometheus/prometheus.ClusterRole.yaml

A customer applied this patch to their Prometheus cluster role so they could use https://github.com/braedon/prometheus-es-exporter

update prometheus cluster role so it can provide node metrics

---

base/indexed-search/indexed-search.Deployment.yaml

This brings in https://github.com/sourcegraph/zoekt/pull/8.

update zoekt-webserver to include indexed multiline fix

---

README.dev.md

This adds a short guide containing the commands I ran to deploy to
minikube. This guide is rough and likely only useful to Sourcegraph devs, so
we add it to our internal documentation.

README.dev: Add instructions for using minikube

---

base/syntect-server/syntect-server.Deployment.yaml

Various deployments we have show that with some languages syntect_server
consumes more memory and OOMs. Bumping this up to 4 GB makes sense and
has worked well in customer deployments that previously had issues.

base/syntect-server: increase memory from 512 MB -> 4 GB

---

base/lsif-server/lsif-server.Deployment.yaml
base/lsif-server/lsif-server.PersistentVolumeClaim.yaml
base/lsif-server/lsif-server.Service.yaml

This adds lsif-server that was introduced in https://github.com/sourcegraph/sourcegraph/pull/4799
lsif-server is a service that sits behind Sourcegraph's frontend and exposes an HTTP API that receives file uploads and stores them on disk. That storage is expected to stick around for the lifetime of the Sourcegraph instance.
TODO

Add lsif-server

---

base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/management-console/management-console.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml

After waiting on renovate bot for an hour I decided to do this by hand by collecting the SHAs from the build output in this build:
https://buildkite.com/sourcegraph/sourcegraph/builds/40709#aa8f45c0-b4e6-481c-bb91-c4e8335fc4de

Update Sourcegraph Docker images Docker tags to v3.5.4

---

docs/k8s.eks.md
docs/k8s.md

- t2.xlarge only has 4 CPU cores. Some of our services require 6 cores (e.g. postgres, zoekt), so these nodes are insufficient. 
- Some quick calculations show that we need ~30 cores and ~26G RAM just for all of our services in `base/`
- `m5.4xlarge` is close to the machine type what we're using for sourcegraph.com (`n1-standard-16` - `16 cores and 60 gigs of ram`)
- k8s has a roughly equal packing (~30% requested CPU) when we use 4 `m5.4xlarge` nodes for the base deployment (no tuning)

update aws scaling docs

---

base/grafana/grafana.ConfigMap.yaml
base/grafana/grafana.Service.yaml
base/prometheus/prometheus.Service.yaml

Fixes: https://github.com/sourcegraph/sourcegraph/issues/5536
avoid requiring elevated permissions for privileged ports.
see:
**https://stackoverflow.com/questions/53775328/kubernetes-port-forwarding-error-listen-tcp4-127-0-0-188-bind-permission-de/55023272#55023272**

avoid privileged ports

---

docs/migrate.md

This information is now outdated and, if updated, would just restate what is already stated in the linked migration guide. So, instead, let's just link to that migration guide.

docs/migrate: remove outdated 3.7 migration information and link to docs

---

base/lsif-server/lsif-server.Deployment.yaml
base/lsif-server/lsif-server.Service.yaml
docs/configure.md

This will be necessary after https://github.com/sourcegraph/sourcegraph/pull/5525.

Update lsif-server deployment to support worker metrics.

---

base/syntect-server/syntect-server.Deployment.yaml

- This PR updates syntect-server to the new HA implementation which internally runs 4 workers.
- Each worker can at peak use ~1.1 GiB, so a 6G memory limit is now suggested.
- The number of workers can be tuned using the env var `WORKERS`. Setting it to `1` would retain the old resource requirements but still be more stable. In practice, tuning it should not be needed.
- A Prometheus metric is also exposed by the container on `:6060/metrics` called `syntect_server_hss_worker_restarts` to measure worker restarts (any restarts indicate a bug in syntect_server).
- For more details, see the first commit message in https://github.com/sourcegraph/syntect_server/pull/25
Closes sourcegraph/sourcegraph#5406

Update syntect-server to HA implementation (runs 4 workers internally)

---

base/grafana/grafana.Deployment.yaml

- moves default port to 3370
- upgrades underlying grafana to 6.4.1
- fixes jsonnet dashboard generation for single server
- allows grafana to work outside the reverse proxy
related to https://github.com/sourcegraph/sourcegraph/pull/5910

upgrade grafana

---

renovate.json

Is there any reason for changes like this to not get merged automatically? https://github.com/sourcegraph/deploy-sourcegraph/pull/406

Automerge updating docker image tags

---

base/prometheus/prometheus.Deployment.yaml

10.0.2 discovered too many candidates for alertmanager endpoint

prometheus: bump docker image to 10.0.3

---

base/prometheus/README.md

Isn't overall usage what you want to see, instead of rss, when making resource allocation decisions (e.g. are we over/under provisioned on memory)?

Fix memory usage metric

---

base/frontend/sourcegraph-frontend.Deployment.yaml
base/indexed-search/indexed-search.Service.yaml
docs/migrate.md

This was an oversight in 3.9. We require the service to be headless to be able
to get a stable network identify per indexed-search pod.
More context: https://github.com/sourcegraph/sourcegraph/issues/5725#issuecomment-547304388
Part of https://github.com/sourcegraph/sourcegraph/issues/5725

all: Migrate svc/indexed-search to a headless service

---

base/prometheus/prometheus.ConfigMap.yaml

This moves the k8s prometheus config into the ConfigMap providing full external control without the need to rev the prometheus disk image.

prometheus: config file from ConfigMap

---

base/frontend/sourcegraph-frontend.Service.yaml
base/github-proxy/github-proxy.Service.yaml
base/gitserver/gitserver.Service.yaml
base/indexed-search/indexed-search.Service.yaml
base/lsif-server/lsif-server.Service.yaml
base/management-console/mangement-console.Service.yaml
base/pgsql/pgsql.Service.yaml
base/prometheus/prometheus.ConfigMap.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Service.yaml
base/redis/redis-cache.Service.yaml
base/redis/redis-store.Service.yaml
base/replacer/replacer.Service.yaml
base/repo-updater/repo-updater.Service.yaml
base/searcher/searcher.Service.yaml
base/symbols/symbols.Service.yaml
configure/ingress-nginx/mandatory.yaml
configure/lang/go/lang-go.Service.yaml
configure/lang/typescript/lang-typescript.Service.yaml

This changes the scraping annotation for services to sourcegraph.prometheus/scrape.
This makes it less likely that customers with additional prometheus instances running in their cluster will have the same label and it prevents our builtin prometheus from scraping services not related to Sourcegraph. The previous annotation is probably what everybody uses because it's copy/pasted from the prometheus kubernetes docs.
Note: this doesn't address the other scraping roles: nodes, endpoints and pods.
We still want those for our dot-com deployment but I'm not sure how useful they are in a customer deployment context. We can restrict those too (in the same way) or delete them.

prometheus: constrain service scraping to sourcegraph.prometheus

---

docs/configure.md
docs/migrate.md

Thanks to service discovery this is much easier than gitserver. Also adjusted gitserver document to remove references to non existent indexed search PV.
Part of https://github.com/sourcegraph/sourcegraph/issues/5725

docs: Document adjusting the replica count of indexed-search

---

base/frontend/sourcegraph-frontend.Deployment.yaml

The 3.10 docker images of Sourcegraph use service discovery, so do not require
ZOEKT_HOST to be specified. Additionally, the default has been updated to what
the value was specified as. This means we do not need to include this value.
Adding ZOEKT_HOST was added by
https://github.com/sourcegraph/deploy-sourcegraph/pull/428 but was made
obsolete by https://github.com/sourcegraph/sourcegraph/pull/6296. It being
specified just means we do not use service discovery, and does not lead to any
oter problems.

frontend: Do not specify ZOEKT_HOST

---

base/prometheus/prometheus.ConfigMap.yaml

Work for issue:
https://github.com/sourcegraph/sourcegraph/issues/5994
This sets up alerts according to what the gitserver processes see through syscall stats exported as prometheus metrics.

alert: gitserver low disk

---

base/prometheus/prometheus.ConfigMap.yaml

These were lost when config file moved to ConfigMap.

prometheus: pick up rules from container

---

base/gitserver/gitserver.Service.yaml

prometheus needs the app label.
i added it to the selector too. in the next iteration we can remove the type labels from the statefulset and service if we want to make it more uniform.

gitserver: app label for service

---

base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml

This makes it possible to measure resource consumption separately (which is measured at the container level).
For all the other deployments that I spot checked, the container name matches the deployment name.

Distinct container names for redis-store and redis-cache

---

base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/lsif-server/lsif-server.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/replacer/replacer.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml

Renovate has not produced the proper update [within 5 hours](https://sourcegraph.slack.com/archives/CJX299FGE/p1579758914054800) so I produced this change using a script I wrote.
I will publish the script separately and propose we move away from Renovate for updating our Docker image SHAs in specific (not proposing we stop using it for dependency updates in general, or even for third-party Docker images) -- and this will be beneficial to automating more of the release process as well.

Update Sourcegraph Docker image tags to v3.12.1

---

configure/ingress-nginx/README.md
configure/ingress-nginx/cloud-generic.yaml
configure/ingress-nginx/mandatory.yaml

Previously, our nginx pods were failing with the following error: 
```
Failed to list *v1beta1.Ingress: ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot list resource "ingresses" in API group "networking.k8s.io" at the cluster scope
```

nginx-ingress: upgrade to 0.29.0

---

docs/install.md
docs/scale.md

It's really hard to find this in our docs, so I added it to the installation instructions along with the gitserver replicas and linked to the `scale.md` doc.
@keegancsmith That `scale.md` doc is also missing some numbers on Zoekt. That might be valuable to have.

Mention indexed-search scaling in installation instructions

---

base/frontend/sourcegraph-frontend.Role.yaml
base/prometheus/prometheus.ClusterRole.yaml
base/prometheus/prometheus.ClusterRoleBinding.yaml
docs/migrate.md
overlays/non-privileged/frontend/sourcegraph-frontend.RoleBinding.yaml
overlays/non-privileged/kustomization.yaml
overlays/non-privileged/prometheus/prometheus.ConfigMap.yaml
overlays/non-privileged/prometheus/prometheus.RoleBinding.yaml

For new installations that have restrictive security policies in place.
Tested on gke using https://about.sourcegraph.com/handbook/engineering/distribution/k8s_admin_custom_policy
Note: this has to be in a namespace, cannot be in default (cluster-wide) because ClusterRoleBindings became RoleBindings.
Note: Prometheus kubernetes_sd scraping has been limited to service endpoints and constrained to the specified namespace (again because of the restrictions of the role for the prometheus service account.

non-privileged kustomization

---

docs/migrate.md

Makes clear what the two changes are and which one is needed for migrating existing installations.

doc: clarify and separate in migration doc the two changes in 3.14

---

base/gitserver/gitserver.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/lsif-server/lsif-server.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
overlays/migrate-to-nonroot/gitserver/gitserver.StatefulSet.yaml
overlays/migrate-to-nonroot/indexed-search/indexed-search.StatefulSet.yaml
overlays/migrate-to-nonroot/lsif-server/lsif-server.Deployment.yaml
overlays/migrate-to-nonroot/redis/redis-cache.Deployment.yaml
overlays/migrate-to-nonroot/redis/redis-store.Deployment.yaml

in PR https://github.com/sourcegraph/deploy-sourcegraph/pull/534 i made a mistake of just checking
```
id -u <container-user>
```
and assuming group would be the same id. this is just a convention not necessarily true, so this time i checked
```
id -g <container-user>
```
too and made the required changes.
I will test everything one more time (migration and new from scratch and rollback)
NOTE: this all worked before and was tested. the theory is that the fsGroup value makes it work. But having them match exactly is more desirable.

file group ownership matches container user:group

---

overlays/migrate-to-nonroot/frontend/sourcegraph-frontend.Deployment.yaml
overlays/migrate-to-nonroot/kustomization.yaml
overlays/migrate-to-nonroot/searcher/searcher.Deployment.yaml

to kustomization
they are emptyDir volumes which could be affected if pod stays on same node during migration to non-root user and then cannot read/write from the cache
this does not address configure/ssd /mnt/cache volumes.
i will change the pod-tmp-gc daemonset there probably

non-root user migration: add /mnt/cache volumes from base

---

tests/integration/restricted/test.sh

Without timeouts, the integration test can hang indefinitely on the following lines:
```
timeout 5m kubectl -n ns-sourcegraph rollout status -w statefulset/indexed-search                                                                              
timeout 5m kubectl -n ns-sourcegraph rollout status -w deployment/precise-code-intel-bundle-manager                                                            
timeout 5m kubectl -n ns-sourcegraph rollout status -w deployment/prometheus                                                                                   
timeout 5m kubectl -n ns-sourcegraph rollout status -w deployment/redis-cache                                                                                  
timeout 5m kubectl -n ns-sourcegraph rollout status -w …
```

add timeouts to integration test

---

base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/precise-code-intel/api-server.Deployment.yaml
base/precise-code-intel/bundle-manager.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/replacer/replacer.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml

Master is currently broken as the precise-code-intel tags are newer than the frontend tag and precise-code-intel expects a database version that doesn't exist in the 3.14 branch.
This undoes https://github.com/sourcegraph/deploy-sourcegraph/commit/43c8c05e0db99ed8a9d962463fc2fba58df43090#diff-617545faa1b764ea0cf42a0880bc2cef

Update image tags to latest master build

---

base/grafana/grafana.PersistentVolumeClaim.yaml

Grafana disk usage is only 60mb on k8s.sgdev.org and sourcegraph.com, so why do we ask for 200gb? Fixes https://github.com/sourcegraph/deploy-sourcegraph/issues/387.

reduce grafana pvc from 200Gi to 2Gi

---

docs/configure.md

We do not use a separate DB, this behavior was removed before 3.9.x was released.

docs/configure: remove incorrect statement

---

.buildkite/integration-restricted-test.sh

this is temporarily so i can push releases out.
will fix soon. i have to collect all the restrictions because it keeps biting me

restricted test: cluster labels have temporarily hardcoded values

---

base/jaeger/jaeger.Deployment.yaml
dockerfiles/jaeger/all-in-one/Dockerfile
dockerfiles/jaeger/all-in-one/Makefile
dockerfiles/jaeger/all-in-one/build.sh
dockerfiles/jaeger/all-in-one/upload.sh
dockerfiles/jaeger/all-in-one/version.sh

This addresses https://github.com/sourcegraph/deploy-sourcegraph/pull/559#discussion_r405182789
Post-merge:

jaeger-all-in-one: non-root permissions on /tmp

---

create-new-cluster.sh

rbac-roles cannot be added to overlays/non-root-create-cluster because that overlay is used as base by the non-privileged-create-cluster where these roles are not allowed (kustomize does not support delete)

new cluster needs rbac roles

---

tests/integration/fresh/fresh_test.go

1.16 got pull out of gke rapid release channel

testing: replace 1.16 with 1.17 in GKE testing list

---

overlays/non-root/gitserver/gitserver.StatefulSet.yaml

Documents where to mount ssh config for gitserver in non-root overlay.
See https://github.com/sourcegraph/deploy-sourcegraph/pull/571 also

non-root: document mount path for ssh config

---

base/grafana/README.md
overlays/minikube/README.md
overlays/namespaced/README.md
overlays/namespaced/kustomization.yaml
overlays/namespaced/prometheus/prometheus.ClusterRoleBinding.yaml
overlays/non-privileged-create-cluster/README.md
overlays/non-privileged/README.md

Clean up in README instructions and patched a `namespaced` overlay omission (the namespace value needs to be set in the cluster rolebinding for prometheus)

overlays: readme fixes and namespaced prometheus rbac

---

.github/PULL_REQUEST_TEMPLATE.md

Today, changes are sometimes made to the Kubernetes deployment with changes to deploy-sourcegraph-docker (Docker Compose & "Pure Docker") deployments being updated after the fact.
This PR adds a PR template which enforces we be mindful of keeping the two repositories up to date and in sync, which will allow us to release Docker Compose on the same date (20th of every month) as all of our other deployment methods.
See sister change: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/103

add PR template to keep Kubernetes and Docker Compose in sync

---

base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/bundle-manager.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
docs/migrate.md

addresses sourcegraph/sourcegraph#2076 as an example of what can be applied to other services.
Assuming customers have deployed this using `kubectl apply` and not `kubectl create` no other scripting should be required to change this property on the deployment.

migrating update strategy to recreate

---

.github/workflows/lsif.yml

The LSIF indexing action added in #666 was getting pulled into forks and causing CI errors. This change causes it to only run on the current repo.

only run LSIF indexing on this repo, not forks of it

---

docs/k8s.eks.md
docs/k8s.md

closes https://github.com/sourcegraph/sourcegraph/issues/9724
https://github.com/sourcegraph/deploy-sourcegraph/blob/docs/aws-eks/docs/k8s.md
Some comments (mostly based on https://github.com/sourcegraph/sourcegraph/issues/9724):
* as pointed out in the ticket it seems that the EKS getting-started guide for nodegroups differs from the nodegroup-specific documentation (https://docs.aws.amazon.com/eks/latest/userguide/worker_node_IAM_role.html), but the docs here follow the getting started guide, so it should be safe to stick with?
* updated the format of the `k8s.md` table to hopefully make it more clear that some of those links point to sourcegraph-specific setup
* fixed a number of outdated links
I ran it through the Sourcegraph install steps too - first time around, I configured …

docs: update k8s.eks

---

base/precise-code-intel/worker.Deployment.yaml

500M/2G is far too low. A test cluster OOM churned running the precise-code-intel integration tests. Upping the memory a bit stopped the crash loop.

Up default memory limit for precise-code-intel-worker

---

base/frontend/sourcegraph-frontend.Deployment.yaml

for https://github.com/sourcegraph/sourcegraph/pull/10704 - adds `PROMETHEUS_SERVER_URL` to allow the frontend to query metrics.
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/108

add prometheus server URL

---

base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/api-server.Deployment.yaml
base/precise-code-intel/bundle-manager.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/replacer/replacer.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

using stephen's update bot (thanks for that !)
sister PR comes later in the release captain checklist

update docker image tags to 3.16.0

---

base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.Deployment.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/api-server.Deployment.yaml
base/precise-code-intel/bundle-manager.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/replacer/replacer.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

image tags: upgrade to 3.15.2

---

base/frontend/sourcegraph-frontend.Deployment.yaml

Fixes https://github.com/sourcegraph/sourcegraph/issues/10491
Tested with "index.docker.io/sourcegraph/frontend:insiders@sha256:a5b2eadbab0c0d2fda9bccddcad4e62d6816a9aff6898dedd93e8a65c8e4f26b" &
index.docker.io/sourcegraph/jaeger-all-in-one:insiders@sha256:7b3d2f619ef8d15a62d25ab42688251baeb16dbe3a5924a7cf2a9699adf8d8ab
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/116

Add env var to frontend deployment for Jaeger

---

overlays/README.md

Missed this readme when i scrubbed the docs and moved them to docs.sourcegraph.com
no overlays there (thank goodness :-) )

docs: point leftover overlay readme to sourcegraph docs instead

---

base/indexed-search/indexed-search.IndexerService.yaml
overlays/bases/deployments/kustomization.yaml
overlays/minikube/grafana-patch.yaml
overlays/minikube/kustomization.yaml

both zoekt webserver and indexers are now scraped by prometheus
this PR also has small fixes for things found during testing the scraping on minikube and on bigdata test cluster

monitoring: add second service to indexed search to expose prom scrape

---

base/grafana/grafana.ConfigMap.yaml

depends on https://github.com/sourcegraph/sourcegraph/pull/11583
context: grafana 7 has built-in jaeger support
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/120

grafana: add jaeger datasource

---

kubectl-apply-all.sh

Add note to advise users that --prune is destructive and should always be applied to base directory. Address concern in sourcegraph/sourcegraph#11913

update advice for --prune flag

---

base/prometheus/prometheus.ConfigMap.yaml

Add builtin Alertmanager as a target, and add a label for each builtin alert:
* `level: critical` to replace `severity: page`
* `level: warning` otherwise
I believe `severity: page` is used for our current dot-com opsgenie pages, will probably not apply the `severity: page` removal immediately to dot-com (https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/2839)
For https://github.com/sourcegraph/sourcegraph/issues/5370
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change: n/a

prometheus: add builtin alertmanager, labels.level for builtin alerts

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/bundle-manager.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/replacer/replacer.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

Co-authored-by: Renovate Bot <bot@renovateapp.com>

Update Sourcegraph Docker images Docker tags to v3.17.3 (#780)

---

base/prometheus/prometheus.ConfigMap.yaml
kubectl-apply-all.sh

for https://github.com/sourcegraph/sourcegraph/issues/12026
Adding labels.level to these alerts in https://github.com/sourcegraph/deploy-sourcegraph/pull/784 means that admins can get notifications for them via `observability.alerts`, however they don't have the same set of labels as our generated alerts, so notifications are a bit lackluster
This PR adds labels `name`, `service_name`, `description` to align them with our generated alerts as a stopgap until https://github.com/sourcegraph/sourcegraph/issues/12117
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change: n/a, these alerts only exist here
Will follow up with an update to dot-com

prometheus: add consistent alert labels

---

base/indexed-search/indexed-search.StatefulSet.yaml
base/searcher/searcher.Deployment.yaml

These services when searching will use a lot of CPU and IO. This may
make them slow to respond. The readiness probe failing has disasterous
consequences, since k8s' service discovery will remove the pod from the
endpoint list leading to us rebalancing.
This is a guess at a root cause of problems we are seeing on a very
large instance.

search: generous timeout for search pods

---

base/repo-updater/repo-updater.Deployment.yaml

corresponds to https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/2975
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change: n/a, there are already similar resources configured there https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/deploy-repo-updater.sh

repo-updater: bump cpu, memory

---

base/prometheus/prometheus.ConfigMap.yaml

Removes all the alerts that have been migrated in https://github.com/sourcegraph/sourcegraph/pull/12391, for https://github.com/sourcegraph/sourcegraph/issues/12117

prometheus: remove custom alert rules and records, scrape prometheus

---

base/prometheus/prometheus.ConfigMap.yaml

closes https://github.com/sourcegraph/sourcegraph/issues/12482
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change: n/a

add app label for prometheus, alertmanager

---

base/indexed-search/indexed-search.StatefulSet.yaml
base/searcher/searcher.Deployment.yaml

Change the failureThreshold and periodSeconds of searcher and
indexed-searcher to be less strict.
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/130

Increase minimum failureThreshold and periodSeconds

---

base/prometheus/prometheus.ConfigMap.yaml

mirrors https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/f234bcbd56f1b57f34a47c7992be65e933124f9b by @beyang 

prometheus: drop jaeger-agent containers

---

tests/integration/fresh/fresh_test.go

It seems that 1.14 might no longer be available for masters:
```
gcp:container:Cluster ds-integ-fresh-test-cluster **creating failed** error: googleapi: Error 400: Master version "1.14.10-gke.46" is unsupported., badRequest
```
I'm unable to find any documentation supporting this other than an [Aug 6 GKE change indicating that 1.14 masters and nodes are being upgraded to 1.15 automatically](https://cloud.google.com/kubernetes-engine/docs/release-notes#august_06_2020_r26), but @davejrt poked around in the UI and it seems that 1.14 is no longer available in the console.
This change also adds 1.16 to replace 1.14, since it's missing. There is 1.18, but it seems that it is not GA yet

tests: drop k8s 1.14, add 1.16

---

base/jaeger/jaeger.Deployment.yaml

jaeger: make cpu limit field text (needed by dhall migrator)

---

.github/workflows/dispatch-update.yml

for https://github.com/sourcegraph/sourcegraph/issues/13121
Adds an action that dispatches a notification that `deploy-sourcegraph` has been updated to https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s-2 , which then uses the payload to apply the update.
The information dispatched here is pretty minimal and unlikely to change, so I am marking this as ready for review. The https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s-2 is good to go, just need to add auto-merge
Note: recent tests fail because the new merge strategy won't work with diverged histories
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change: n/a

create update dispatch workflow

---

renovate.json

This (hopefully) configures renovate to set up a PR with insiders images for this repo as part of https://github.com/sourcegraph/sourcegraph/issues/13122 . Automerge is currently not enabled so that I can verify this.
I'm hoping, along with https://github.com/sourcegraph/sourcegraph/pull/13449, that we can get to a state where commits to Sourcegraph land in this repo and then to downstream repos like https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s-2 relatively quickly.
**Generating releases**: I'm not entirely sure how we generate releases yet with this new setup - I think we'll have to branch and update images and tag there
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change: This change was not planned for …

update renovate to use insiders for sourcegraph docker images

---

README.md

* Links to admin guide and metrics guide were 404
* Adjust warning to below the header, since I found myself [missing the pre-header warning entirely](https://github.com/sourcegraph/deploy-sourcegraph/pull/845#issuecomment-685727888), and adjust the checkout instructions to [recommend a branch instead](https://github.com/sourcegraph/deploy-sourcegraph/pull/845#issuecomment-686017721)
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change: n/a

fix links to admin and metrics guides, adjust warning

---

renovate.json

Renovate is erroring on the `followTag` setting, so I'm just getting rid of it - this aligns it with how dot-com is configured https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/renovate.json#L10-L23
https://app.renovatebot.com/dashboard#github/sourcegraph/deploy-sourcegraph/227259180
follow-up to #845

renovate: align with dot-com settings

---

renovate.json

I'm still unable to get Renovate to run a config locally (the CLI can only look at local config, which renovates remote repositories, so I can't seem to test config changes...)
This change attempts to get Renovate to accept "insiders" tags as "upgrades"

renovate: upgrade to insiders

---

.github/workflows/release.yml
.github/workflows/scripts/update-docker-tags.sh
.github/workflows/update-tags.yml
README.dev.md
base/cadvisor/cadvisor.DaemonSet.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/bundle-manager.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml
renovate.json

Another stab at https://github.com/sourcegraph/sourcegraph/issues/13122 because Renovate is a bit of a bummer. Also see [new rendered docs](https://github.com/sourcegraph/deploy-sourcegraph/blob/switch-to-insiders/README.dev.md).
* ~Use `BUILD_YYYY` versioning scheme to track `insiders` - have Renovate interpret these versions as `v0.YYYY.BUILD` and upgrade accordingly, where `BUILD` is the Buildkite build number. Makes it more clear what is deployed. I'm happy to roll this back too, since I was having trouble getting Renovate to play well with `insiders` and performing releases, but now that I've dropped Renovate for generating releases, it should be fine to have `insiders` like we do on dot-com. See the current state of versions for what this might look like, and see the `"versioning"` …

rework versioning and release scheme

---

renovate.json

Reduce noise from renovate cloud, since we now have a [custom renovate trigger for this repository in sourcegraph/sourcegraph ](https://github.com/sourcegraph/sourcegraph/blob/main/.github/workflows/renovate-downstream.yml), which will override this schedule (https://github.com/sourcegraph/sourcegraph/pull/13761).
Also, this is partly because there doesn't seem to be a good way to exclude certain repositories from renovate cloud
Thinking it might be best to keep a weekly run as a fallback

renovate: add weekly schedule

---

renovate.json

Closes https://github.com/sourcegraph/sourcegraph/issues/13122
Renovate is rolling: https://github.com/sourcegraph/deploy-sourcegraph/pull/859

renovate: enable automerge for sourcegraph insiders

---

renovate.json

Config not getting overwritten at the top level: https://github.com/sourcegraph/sourcegraph/runs/1107121150?check_suite_focus=true#step:5:368 , and no PRs are getting triggered
I can find no issues/documentation on this problem, even though all the docs indicate that the current set up should work 🤔 

renovate: move schedule to packageRules

---

renovate.json

Reverts sourcegraph/deploy-sourcegraph#864 - didn't do anything

Revert "renovate: move schedule to packageRules"

---

base/gitserver/gitserver.StatefulSet.yaml

Anyone who configures gitserver to use an SSH might be encountering a conflict here all the time whenever `jaeger-agent` is updated - see https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s-2/pull/35/commits/bce416e6fb8ba98e922e0c126dd452c7da6ac9b3#diff-0af75dcdf933574bfb06b86a1d41238e
This PR moves the image definition down one line to hopefully reduce the chance it'll conflict again

move image field one line to avoid conflict on image update

---

.github/workflows/lsif.yml

Based on frequency of commits to Sourcegraph, these can behave strangely on the renovate insiders branches (which tries to pick up the latest images as soon as possible)

lsif: disable workflow on renovate docker insiders branches

---

.github/workflows/automerge.yml
renovate.json

Renovate merge requires a renovate run, but we can typically merge as soon as CI finishes (ie before the next renovate run). This will reduce time-to-update from Sourcegraph to deploy-sourcegraph

Use automerge action instead of renovate merge

---

.github/workflows/automerge.yml
renovate.json

Brings back https://github.com/sourcegraph/deploy-sourcegraph/pull/886
This should work now that I've set the buildkite to be a required check
> Renovate merge requires a renovate run, but we can typically merge as soon as CI finishes (ie before the next renovate run). This will reduce time-to-update from Sourcegraph to deploy-sourcegraph

Use automerge action instead of renovate merge (take 2)

---

base/cadvisor/README.md
base/prometheus/README.md
base/prometheus/prometheus.Deployment.yaml
overlays/namespaced/README.md
overlays/namespaced/cadvisor/cadvisor.ClusterRoleBinding.yaml
overlays/namespaced/kustomization.yaml

The dogfood k8s environment is deployed in a namespace, `dogfood-k8s`, and Prometheus ran into two issues:
* there was no associated ServiceAccount - this change sets the service account explicitly, similar to what is done in the cAdvisor daemonset
* the service account was in the wrong namespace - there is a kustomization available for this, which I've updated to include an overlay for the cAdvisor account. I've also updated docs for both cAdvisor and Prometheus to indicate this.
See https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s-2/pull/98

ClusterRole namespaces

---

.github/workflows/update-tags.yml

Noticed https://github.com/sourcegraph/deploy-sourcegraph/pull/914 did not generate a very useful message 😅 

chore: update to create-pull-request@v3, set better commit message

---

.buildkite/cleanup-unused-disks.sh
.buildkite/integration-restricted-test.sh
.buildkite/integration-test.sh
README.dev.md
tests/integration/fresh/fresh_test.go
tests/integration/fresh/step1/config.ts
tests/integration/fresh/step1/index.ts
tests/integration/restricted/test.sh

Remove the explicit `dev` buildkite account definitiona and use the
account already associated with the GKE nodes which has the correct
permissions.
This change also uses `sourcegraph-ci` as the target project for
ephemeral test clusters.

User implicit CI service account for tests

---

.buildkite/verify-yaml.sh

Reflects @pecigonzalo 's change over at https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/3516 back upstream to this repo. Currently blocking automated updates: https://github.com/sourcegraph/deploy-sourcegraph/pull/985

buildkite: fix verify-yaml script

---

base/frontend/sourcegraph-frontend.RoleBinding.yaml
base/prometheus/prometheus.ClusterRoleBinding.yaml
base/prometheus/prometheus.Deployment.yaml
overlays/non-root/pgsql/pgsql.Deployment.yaml

- service account in prometheus specified twice
- api group for cluster role binding
- non-root security context for pgsql needs to override base one at top-level too (not just in container specs)

cleanup of small warts in the manifest specification

---

.gitignore

Ignore dhall files for security reasons (see [security issue 8](https://github.com/sourcegraph/security-issues/issues/8))
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/161) change:

Ignore dhall files

---

tests/integration/restricted/test.sh

**Update - see https://github.com/sourcegraph/sourcegraph/issues/14728 for context**
---
Attempting to fix CI failures in this repository: https://github.com/sourcegraph/deploy-sourcegraph/pull/1067
https://github.com/kubernetes/kubernetes/issues/85314#issuecomment-608820993

test(restricted): change resource flag, pin to kubernetes 1.15

---

base/prometheus/prometheus.Deployment.yaml

Prometheus in k8s.sgdev.org recently got itself in a OOMKilled CrashLoopBackoff (https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s-2/pull/229). It's not a very busy deployment, so this probably warrants a bump in the requirements.
The comment was also a bit outdated - Prometheus in Cloud now gets 8G, not the 3G claimed here, so I set a new limit at 8G.

prometheus: increase memory limit

---

.github/workflows/scripts/update-docker-tags.sh
.github/workflows/update-tags.yml

This should fix https://github.com/sourcegraph/sourcegraph/issues/14925 by ensuring that the release tool user's local PATH/GO setup does not interfere with the correct update-docker-tags version that should be used

chore: use go run for update-docker-tags

---

base/minio/minio.Deployment.yaml
base/minio/minio.PersistentVolumeClaim.yaml
base/minio/minio.Service.yaml

This adds a MinIO deployment. Part of https://github.com/sourcegraph/sourcegraph/issues/14825.
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/169

Add MinIO deployment

---

base/minio/minio.Deployment.yaml

https://medium.com/faun/minio-object-storage-deployment-on-kubernetes-83f81fba1d03

Update minio.Deployment to use 'args' instead of 'command'

---

base/minio/minio.Deployment.yaml

The deployment is currently failing with 
```
Readiness probe errored: strconv.Atoi: parsing "http": invalid syntax | Unhealthy | Nov 12, 2020, 5:33:20 PM | Nov 12, 2020, 5:43:15 PM | 120 |  
Liveness probe errored: strconv.Atoi: parsing "http": invalid syntax | Unhealthy | Nov 12, 2020, 5:34:23 PM | Nov 12, 2020, 5:34:43 PM | 3 |  
```
I believe this is due to the port reference being incorrect.

Fix the minio probes port reference

---

base/codeintel-db/codeintel-db.Deployment.yaml

Closes https://github.com/sourcegraph/sourcegraph/issues/15206. It looks like deploy-sourcegraph-docker is fine (and cloud doesn't use this service, it uses cloudsql).

codeintel-db: Add insiders tag

---

README.dev.md

releasing: note that step is done by release tool

---

overlays/bases/deployments/kustomization.yaml
overlays/bases/pvcs/kustomization.yaml

This should fix the tests in this repo, and actually correct the generate overlay scripts as minio was not added and it was not being generated/deployed.
We should review and fix this tests/overlay as its quite messy at the moment and tricky to do correctly or even debug.

Add minio to overlays

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.22.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.22.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/15023

release: sourcegraph@3.22.0

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/automerge.yml
go.mod
go.sum
renovate.json
tools/enforce-tags/main.go
tools/tools.go
tools/update-docker-tags.sh

Generates update-docker-tag args from the master list over in `sourcegraph/sourcegraph` (https://github.com/sourcegraph/sourcegraph/pull/16227) instead of requiring manual maintenance. Closes https://github.com/sourcegraph/sourcegraph/issues/15896
As a reminder, we can't just wildcard `sourcegraph/*` images during version enforcement because we have images that don't conform to our standard versioning (e.g. `sourcegraph/alpine`)
The entrypoint remains the same, so this will not break our tooling/CI that now depends on the script.

tools: generate update-docker-tags args from sourcegraph/sourcegraph

---

go.mod
go.sum
renovate.json

It seems this does not work well yet with Sourcegraph's versioning

do not automerge images package updates

---

renovate.json

This generates updates like this: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/189

renovate: only update images list by commit, automerge

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.22.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.22.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/16531)

release: sourcegraph@3.22.1

---

tests/integration/restricted/validate.json

Tests are failing every now for `src validate` due to the repo https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/6346#de9c4017-8673-4d91-bdbe-a758635d1cd4 not being cloned.
Given they pass every now and then, I assume this is just a matter of increasing the timeout.

Wait longer for repos to be cloned

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.23.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.23.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/16108)

release: sourcegraph@3.23.0

---

base/frontend/sourcegraph-frontend.Deployment.yaml

A few adjustments to alleviate a few pain points:
* Keep high-change fields away from each other to avoid conflicts (such as https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s-2/pull/737/files#diff-ec7bc0ca662869dbbc2ef4d656c14002c792de90b497619eacc312397347905d - custom env variables cause perpetual conflicts on image changes because the fields are next to each other
* Scrolling down 50 lines to find the name of a container feels less than ideal

frontend: reorder fields to avoid conflicts and improve readability

---

tests/integration/restricted/test.sh

Fixes:
```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Master version "1.15.12-gke.20" is unsupported.
 
```

bump k8s version

---

base/codeintel-db/codeintel-db.Deployment.yaml
tests/integration/restricted/test.sh

The codeintel DB cannot use the sourcegraph/postgres-exporter image today since it does not contain a migration table which our the sourcegraph/postgres-exporter queries for. 
This causes the exporter for code intel to continually emit errors
Found during https://github.com/sourcegraph/sourcegraph/pull/17131

Switch back to wrouesnel postgres exporter

---

base/cadvisor/cadvisor.ClusterRoleBinding.yaml
base/prometheus/README.md
base/prometheus/prometheus.ClusterRoleBinding.yaml
base/prometheus/prometheus.ConfigMap.yaml

Simpler take on https://github.com/sourcegraph/deploy-sourcegraph/pull/1578 - leaving that open to reassess options. See that PR + discussion for more details. Part of work that closes https://github.com/sourcegraph/sourcegraph/issues/17069.

prometheus: add config for filtering cadvisor metrics by namespace

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.24.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.24.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/17144)

release: sourcegraph@3.24.0

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.24.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.24.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/17770)

release: sourcegraph@3.24.1

---

base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeinsights-db/codeinsights-db.PersistentVolumeClaim.yaml
base/codeinsights-db/codeinsights-db.Service.yaml
base/codeinsights-db/codeinsights.db.ConfigMap.yaml
base/codeintel-db/codeintel-db.ConfigMap.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/codeintel-db/codeintel-db.PersistentVolumeClaim.yaml
base/codeintel-db/codeintel-db.Service.yaml
overlays/non-root-create-cluster/codeinsights-db/codeinsights-db.Deployment.yaml
overlays/non-root/codeinsights-db/codeinsights-db.Deployment.yaml

This PR adds the Code Insights TimescaleDB deployment, which will be used to
store time series data for tracking insights about code. For more information
on what this will be used for, see https://github.com/sourcegraph/sourcegraph/issues/17218
TimescaleDB is a plugin for Postgres which extends it to support time series
data storage. We only use the OSS version, and so deploying it is always free
(and their non-free version supports our use case anyway.)
People deploying Sourcegraph should use this deployment and not try to deploy
TimescaleDB as a plugin in their Postgres deployment for a few reasons:
1. TimescaleDB only supports specific Postgres versions, e.g. not Postgres 13
yet.
2. TimescaleDB should have isolated resources from the rest of Sourcegraph, so
as to prevent Code Insights …

add codeinsights-db (TimescaleDB) deployment

---

base/frontend/sourcegraph-frontend.Deployment.yaml

I missed this by accident, and it prevented the frontend from starting
up (I could have set `DISABLE_CODEINSIGHTS=true` to escape, though):
```
$ kubectl -n prod logs sourcegraph-frontend-687546fb9-62nrn frontend
failed to initialize insights: Failed to connect to codeinsights database: DB not available: failed to connect to `host=127.0.0.1 user=root database=sg`: server error (FATAL: password authentication failed for user "root" (SQLSTATE 28P01))
```
Filed issue to make frontend not block on codeinsights in general: https://github.com/sourcegraph/sourcegraph/issues/18388
Signed-off-by: Stephen Gutekanst <stephen@sourcegraph.com>

frontend: configure codeinsights DB env var

---

base/codeinsights-db/codeinsights-db.Deployment.yaml

These scripts do not exist in the base image (I based the YAML on codeinsights-db,
where it turns out bakes these scripts into the postgres image we ship.)
I will need to revisit adding these, for now removing so it does not produce broken
deployments.
Signed-off-by: Stephen Gutekanst <stephen@sourcegraph.com>

codeinsights-db: remove liveness/readiness probes

---

base/frontend/sourcegraph-frontend.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml

These initial figures are speculative at best, and customers would need to set these themselves in my cases I imagine depending on deployment size. 
These change also doesn't modify anything in the configure directory. 
fixes https://github.com/sourcegraph/sourcegraph/issues/9604

add limits for ephemeral storage

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.25.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.25.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/17727)

release: sourcegraph@3.25.0

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.25.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.25.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/18609)

release: sourcegraph@3.25.1

---

tests/integration/restricted/test.sh

ci: add "repository" label to integration restricted test

---

base/codeinsights-db/codeinsights-db.Deployment.yaml

I failed to verify `/data` was the correct path (it is for our other Postgres images, but not for this TimescaleDB image), which means codeinsights-db data is not being retained currently. I noticed this because the DB was lost on sourcegraph.com (chart looks empty.)
The good news is that I am actively working on building historical data for insights, so this data loss doesn't really matter - it'll all be rebuilt later.
Fixes https://github.com/sourcegraph/sourcegraph/issues/18704
Signed-off-by: Stephen Gutekanst <stephen@sourcegraph.com>

codeinsights-db: correct data volume path

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.25.2 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.25.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/18737)

release: sourcegraph@3.25.2

---

overlays/minikube/cadvisor/cadvisor.ClusterRoleBinding.yaml
overlays/minikube/kustomization.yaml
overlays/minikube/prometheus/prometheus.ClusterRoleBinding.yaml

fixes:
```
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"rbac.authorization.k8s.io/v1\",\"kind\":\"ClusterRoleBinding\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"cadvisor\",\"app.kubernetes.io/component\":\"cadvisor\",\"category\":\"rbac\",\"deploy\":\"sourcegraph\",\"sourcegraph-resource-requires\":\"cluster-admin\"},\"name\":\"cadvisor\"},\"roleRef\":{\"apiGroup\":\"rbac.authorization.k8s.io\",\"kind\":\"ClusterRole\",\"name\":\"cadvisor\"},\"subjects\":[{\"kind\":\"ServiceAccount\",\"name\":\"cadvisor\"}]}\n"}},"subjects":[{"kind":"ServiceAccount","name":"cadvisor"}]}
to:
Resource: "rbac.authorization.k8s.io/v1, Resource=clusterrolebindings", GroupVersionKind: …
```

update minikube overlay with cluster role bindings

---

.github/workflows/automerge.yml

This prevents this to constantly trigger as `status` triggers too frequntly.

Remove status triggers for automerge

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.26.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.26.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/18640)

release: sourcegraph@3.26.0

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.26.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.26.1)
* No tracking issue exists for this release

release: sourcegraph@3.26.1

---

tests/integration/fresh/fresh_test.go

v1.15 is no longer available
https://cloud.google.com/kubernetes-engine/docs/release-notes#March_29_2021

remove 1.15

---

base/frontend/sourcegraph-frontend.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml

By default we deploy a single replica but these services support
scaling horizontally and can be HA by running 2 replicas.

Increase frontend and precise-code-intel-worker replicas

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml
tests/integration/fresh/fresh_test.go

This pull request is part of the Sourcegraph 3.26.2 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.26.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/19775)

release: sourcegraph@3.26.2

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.26.3 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.26.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/19840)

release: sourcegraph@3.26.3

---

base/frontend/sourcegraph-frontend.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml

We should do the same for all things that can migrate the db.

Update readiness check

---

base/frontend/sourcegraph-frontend.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml

uses different endpoint for liveness and readiness to avoid crashing during large migrations
related: https://github.com/sourcegraph/sourcegraph/issues/19757

use new liveness and readiness endpoint

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml
tests/integration/restricted/test.sh

This pull request is part of the Sourcegraph 3.27.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/19746)

release: sourcegraph@3.27.0

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.27.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20315)

release: sourcegraph@3.27.1

---

.buildkite/verify-release/verify-release.go
base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.27.2 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20377)

release: sourcegraph@3.27.2

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.27.3 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20420)

release: sourcegraph@3.27.3

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.27.4 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20452)

release: sourcegraph@3.27.4

---

base/pgsql/pgsql.Deployment.yaml

This PR updates images that use sourcegraph/postgres-12
[_Created by Sourcegraph batch change `andre/update-postgres12.6-base-images`._](https://k8s.sgdev.org/users/andre/batch-changes/update-postgres12.6-base-images)

Update sourcegraph/postgres-12.6 images to latest

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.27.5 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20948)

release: sourcegraph@3.27.5

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml

This pull request is part of the Sourcegraph 3.28.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.28.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20996)

release: sourcegraph@3.28.0

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml
base/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 3.29.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.29.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/21370)

release: sourcegraph@3.29.0

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml
base/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 3.29.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.29.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/22397)

release: sourcegraph@3.29.1

---

base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml

Related to https://github.com/sourcegraph/deploy-sourcegraph/pull/2369
Fixes https://github.com/sourcegraph/sourcegraph/issues/20869
If these values differ, the pod will be evicted for exceeding its storage allotment

Set ephemeral storage to match cache

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml
base/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 3.30.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.30.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23143)

release: sourcegraph@3.30.1

---

base/codeintel-db/codeintel-db.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml

This PR updates the image name which is now `alpine-3.12` and should resolve this line not being updated by renovate.

update to correct alpine image name

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml
base/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 3.30.2 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.30.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23304)

release: sourcegraph@3.30.2

---

base/frontend/sourcegraph-frontend.Deployment.yaml

In Kubernetes deployments, setting the SRC_GIT_SERVERS environment variable explicitly is no longer needed. Addresses of the gitserver pods will be discovered automatically. Unset it in your frontend.Deployment.yaml to make use of this feature. https://github.com/sourcegraph/sourcegraph/pull/24094

frontend: Remove SRC_GIT_SERVERS env var

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/query-runner/query-runner.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml
base/worker/worker.Deployment.yaml

This pull request is part of the Sourcegraph 3.32.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.32.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/25002)

release: sourcegraph@3.32.0

---

renovate.json

Renovate was disabled a while back [here](https://github.com/sourcegraph/deploy-sourcegraph/commit/95be861085c279ddf6e4e9b0945612a64bf57c44#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57) in favor of renovate-downstream trigger the updates. Renovate-downstream was [removed in September](https://github.com/sourcegraph/sourcegraph/pull/25464) so we haven't been getting automatic updates since.
Once a week updates sounds reasonable to me but open to changing it up.

Re-enable scheduling renovate updates

---

.tool-versions
tests/integration/fresh/step1/.tool-versions

This bumps pulumi to the latest 1.X version and adds node to the test test specific .tools-version. Possibly related issue that we faced: https://github.com/pulumi/pulumi/blob/master/CHANGELOG.md#132-2019-10-16

Update test specific .tools-version

---

.buildkite/integration-test.sh
.buildkite/pipeline.yaml
tests/integration/fresh/fresh_test.go

The integration tests create real GKE clusters to perform validation against multiple Kubernetes versions. It's very common that one cluster will fail validation, while the others succeed. Retrying the test means we have to re-run validation against cluster versions that already passed, which is slow and risks a formerly-successful version failing.
This PR makes it so that we run each Kubernetes version as a separate buildkite step, so that each can be retried individually. It is a short-term answer to reduce the pain until we can put more investment into fixing the flakiness.
Better potential solutions long-term:
- Investigate and resolve the root causes of the flaky tests (debugging the causes has proven difficult)
- Stop using GKE clusters, use kind or similar lightweight Kubernetes …

Run each live cluster test as a separate test for easier retries

---

overlays/migrate-to-nonprivileged/frontend/sourcegraph-frontend.Deployment.yaml
overlays/migrate-to-nonprivileged/gitserver/gitserver.StatefulSet.yaml
overlays/migrate-to-nonprivileged/grafana/grafana.StatefulSet.yaml
overlays/migrate-to-nonprivileged/indexed-search/indexed-search.StatefulSet.yaml
overlays/migrate-to-nonprivileged/minio/minio.Deployment.yaml
overlays/migrate-to-nonprivileged/prometheus/prometheus.Deployment.yaml
overlays/migrate-to-nonprivileged/redis/redis-cache.Deployment.yaml
overlays/migrate-to-nonprivileged/redis/redis-store.Deployment.yaml
overlays/migrate-to-nonprivileged/searcher/searcher.Deployment.yaml
tools/update-docker-tags.sh

The `overlays/migrate-to-nonprivileged` overlays include an image reference, which is unique among the overlays. The `update-docker-tags.sh` was only running against `base` so these overlays were getting skipped during releases and always staying on an old version.
On the fence about whether to include the actual manifest changes here or just the script itself. [Renovate is currently broken](https://github.com/sourcegraph/sourcegraph/issues/29473) in this repo so the other image references are quite out of date. I can revert if preferred.
I don't think this is worth doing a patch for - no customer has mentioned this, and it's been broken for a long time. We can just fix it for going forward.

Run update tag script against overlays

---

.buildkite/pipeline.yaml

migrate to stateless agents. This will stop the rogue python issue we occasionally see.

use stateless agents

---

base/frontend/sourcegraph-frontend.Deployment.yaml
kubectl-apply-all.sh
overlays/migrate-to-nonprivileged/frontend/sourcegraph-frontend.Deployment.yaml
overlays/non-privileged/frontend/sourcegraph-frontend.Deployment.yaml

https://github.com/sourcegraph/sourcegraph/issues/25257 and https://github.com/sourcegraph/sourcegraph/issues/25256
This is the `migrator` job for the generic customer use case where `pgsql`, `codeintel-db`, and `codeinsights-db` are all running in cluster.

migrator: add migrator job and require it to run

---

go.mod
go.sum

https://github.com/sourcegraph/update-docker-tags/releases/tag/v0.10.0
[_Created by Sourcegraph batch change `sourcegraph/bump-update-docker-tags-v0.10.0`._](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/bump-update-docker-tags-v0.10.0)

Bump sourcegraph/update-docker-tags to v0.10.0

---

configure/migrator/migrator.Job.yaml
tools/update-docker-tags.sh

The configure/migrator job isn't picked up by the release automation. We'll probably switch away from this to `sg ops` commands soon but in the meantime this change will work.

Include migrator job in release batch change

---

base/frontend/sourcegraph-frontend.Deployment.yaml
configure/migrator/migrator.Job.yaml

Set some default resource limits on the migrator container. Partially addresses https://github.com/sourcegraph/sourcegraph/issues/32272.
Deployed to a local test cluster and confirmed the migrator ran successfully. Ran `docker stats` while deploying a migrator locally to confirm the numbers looked ok (never got above 7 MB and 7% CPU of one core).

Add resource limits to migrator container

---

base/cadvisor/cadvisor.DaemonSet.yaml
base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/frontend/sourcegraph-frontend.Deployment.yaml
base/github-proxy/github-proxy.Deployment.yaml
base/gitserver/gitserver.StatefulSet.yaml
base/grafana/grafana.StatefulSet.yaml
base/indexed-search/indexed-search.StatefulSet.yaml
base/jaeger/jaeger.Deployment.yaml
base/minio/minio.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml
base/precise-code-intel/worker.Deployment.yaml
base/prometheus/prometheus.Deployment.yaml
base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml
base/repo-updater/repo-updater.Deployment.yaml
base/searcher/searcher.Deployment.yaml
base/symbols/symbols.Deployment.yaml
base/syntect-server/syntect-server.Deployment.yaml
base/worker/worker.Deployment.yaml
configure/migrator/migrator.Job.yaml
overlays/migrate-to-nonprivileged/frontend/sourcegraph-frontend.Deployment.yaml
overlays/migrate-to-nonprivileged/gitserver/gitserver.StatefulSet.yaml
overlays/migrate-to-nonprivileged/grafana/grafana.StatefulSet.yaml
overlays/migrate-to-nonprivileged/indexed-search/indexed-search.StatefulSet.yaml
overlays/migrate-to-nonprivileged/minio/minio.Deployment.yaml
overlays/migrate-to-nonprivileged/prometheus/prometheus.Deployment.yaml
overlays/migrate-to-nonprivileged/redis/redis-cache.Deployment.yaml
overlays/migrate-to-nonprivileged/redis/redis-store.Deployment.yaml
overlays/migrate-to-nonprivileged/searcher/searcher.Deployment.yaml

This pull request is part of the Sourcegraph 3.38.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.38.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/31768)
Autogenerated by release tooling

release: sourcegraph@3.38.0

---

.buildkite/pipeline.yaml

Until we can move to using a pinned Checkov image version – the lack of image
pinning is causing the build step to break unpredictably.
The below checks don't apply as this only changes the build pipeline, not functionality.
Confirm that the build step in question doesn't occur.

Remove the Checkov step from the Buildkite pipeline

---

.buildkite/pipeline.yaml

Part of https://github.com/sourcegraph/sourcegraph/issues/33238
[_Created by Sourcegraph batch change `robert/buildkite-standard-queue-rollback`._](https://k8s.sgdev.org/users/robert/batch-changes/buildkite-standard-queue-rollback)
Test plan: CI!

buildkite: use standard queue

---

.buildkite/hooks/pre-command

Fixes the following error, where there does not appear to be any code checked out in the `BUILDKITE_BUILD_CHECKOUT_PATH`
A green build on this PR

use bash source as run directory

---

base/codeinsights-db/codeinsights-db.Deployment.yaml

Adding this in for monitoring purposes.

insights: Add pg_expoter for codeinsights-db

---

.buildkite/cleanup-disks.sh

This isn't really a failure, but should prevent failures if no disks are listed
disk cleanup step should pass

buildkite: fix cleanup-disks.sh

---

overlays/envoy/README.md
overlays/envoy/gitserver.EnvoyFilter.yaml
overlays/envoy/kustomization.yaml

Add a new envoy filter overlay as an example to resolve the following error for instances that are running service mesh (ex. istio):
```
Strconv.Atoi: parsing "": invalid syntax
```
This error occurs when the service mesh like istio drops trailers for http1 by default. Enable trailers using this overlay resolves the issue.  
Tested locally on a minikube instance with istio enabled

Add envoy filter overlay

---

.buildkite/verify-yaml.sh

this is not a change part of the release process but "cherry-picks" changes from #4158 into the 3.42 branch
(the branch is protected and cherry picking directly does not work)
monitor the pipeline

add changes from "Fix target cluster #4158"

---

tests/integration/restricted/test.sh

It was running against sourcegraph.com, so was a pointless src-cli call.
Test Plan: CI is green

restricted integration: run src version against local version

---

.buildkite/pipeline.yaml

k8s 1.20 is no longer available for testing
green tests on CI

fix k8s test versions

---

go.mod
go.sum

Just updates the pinned version of the images in the `4.0` branch so that we can run the `update-images` script. 
Tested that `./update-images.sh` works with an updated list of images.

Update pinned version of docker images

---

.tool-versions
tests/integration/fresh/step1/.tool-versions

This release of the pulumi binary has been removed from github. CI can work well without it, so this should unblock the release process.
See if CI goes green without it.

Try to remove pulumi from asdf dependencies

---

.github/workflows/update-tags.yml
.tool-versions

Update to 1.19.6 because it fixes a bunch of CVEs.
[_Created by Sourcegraph batch change `jhchabran/update-to-go-1.19.6`._](https://sourcegraph.sourcegraph.com/users/jhchabran/batch-changes/update-to-go-1.19.6)
Test Plan: CI

Update to Go 1.19.6

---

configure/executors/executor/executor.Deployment.yaml
configure/executors/private-docker-registry/private-docker-registry.Deployment.yaml

This PR fixes an issue with the metadata on the private docker registry. It also adds in an updated image with NO cve's and limits the scratch storage to avoid the pod being evicted for causing disk pressure based on the docs. 
It also fixes the liveness/readiness probes for the executor. 
Tested on dogfood.

executors: fix bugs in manifests

---

tests/integration/restricted/install-src.sh
tests/integration/restricted/test.sh
tests/integration/restricted/validate.json

Update integration tests to use newer version of `src-cli`:
* Update `src-cli` version used in integration tests to latest 5.0.2 version.
* Update `validate.json` schema to reflect new version.
* Add workaround for `src-cli admin create` bug that outputs token to stderr instead of stdout.
* Fix https://github.com/sourcegraph/sourcegraph/issues/48093
* N/A [CHANGELOG.md](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) updated
* N/A [K8s Upgrade notes updated](https://github.com/sourcegraph/sourcegraph/blob/main/doc/admin/updates/kubernetes.md)
* N/A Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change:
* N/A All images have a valid tag and SHA256 sum
Changes are to tests themselves.

Fix: update `src-cli` version to latest for tests

---

.tool-versions

Update to 1.19.8 because it fixes multiple vulnerabilities.
[_Created by Sourcegraph batch change `evict/update-to-go1.19.8`._](https://sourcegraph.sourcegraph.com/users/evict/batch-changes/update-to-go1.19.8)
Ran locally.

Update to Go 1.19.8

---

configure/embeddings/embeddings.Deployment.yaml
configure/executors/dind/executor.Deployment.yaml
configure/executors/k8s/executor.Deployment.yaml

This shouldn't happen. We need to work out what happened in our release tooling. I did this manually by just visiting the respective pages on dockerhub.
Test Plan: docker pull each image.

update insiders to 5.2.1 tags

---

release.yaml

Until we merged this on `main` on sg/sg, we had to use a custom built sg that we uploaded on a GCS bucket
While I was looking at this repo, I think we should make configurable which registry to use, sounds like having a default value in the env bit at the beginning of the manifest would be neat. 
> NOTE:
CI

chg/rel: use normal `sg` instead of custom one

---

.buildkite/pipeline.yaml

Use standard `sg` instead of hardcoded one. 
> NOTE:
Plugin was tested in https://github.com/sourcegraph/deploy-sourcegraph-k8s/pull/102

chg/rel: update pipeline to use default sg

---

release.yaml

I'm worried that the `qa-` prefix in the tags here is going to mess up pings logic for latest version see: 
https://linear.app/sourcegraph/issue/REL-85/admin-updates-page-updates-page-not-displaying-latest-releases
> NOTE:
No test required here

Release Tooling: remove qa- from branch creation and tag naming during release

---

base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml

Fix Redis readinessProbe
https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/458
> NOTE:
Deploy locally

Fix Redis readinessProbe

---

base/redis/redis-cache.Deployment.yaml
base/redis/redis-store.Deployment.yaml

fix the readiness probe fix, to correctly handle for passwords
> NOTE:
tested with and without password on kind

fix redis readiness to handle for no password

---

overlays/jaeger/jaeger-collector.Service.yaml
overlays/jaeger/jaeger.Deployment.yaml
overlays/jaeger/otel-collector.Deployment.yaml

Resolves [REL-171](https://linear.app/sourcegraph/issue/REL-171/cve-2024-36129-deploy-sourcegraph) for this repo
Manual testing

fix(otel): Update jaeger config

---

base/codeinsights-db/codeinsights-db.Deployment.yaml
base/codeintel-db/codeintel-db.Deployment.yaml
base/pgsql/pgsql.Deployment.yaml

Use the postgres 16 containers
> NOTE:
CI

fix: use postgres 16 containers for db

---

base/gitserver/gitserver.StatefulSet.yaml

This adds a startup probe to gitserver so that it's not immediately killed while it's starting up and migrating the on-disk format for repos.
Passed linters, ran it locally, plan to exercise it when we deploy to s2 and dotcom.

add gitserver startup probe

---

base/frontend/sourcegraph-frontend.Deployment.yaml

Linear issue [REL-812: Update deployment types](https://linear.app/sourcegraph/issue/REL-812/update-deployment-types)
Instances with deployment type "Kubernetes" are too vague to be useful in telemetry. Setting this now, so that we can start identifying these usefully in Telemetry as customers upgrade their legacy Kustomize instances >= 6.2.0
> NOTE:
Test in Looker

Chore: Fix deployment types in telemetry
