- templates/gitserver/gitserver.Deployment.yaml
See https://github.com/sourcegraph/infrastructure/pull/574
> gitserver: Include tracing env

- README.dev.md
Add steps to cut a release in this repository.
> Add steps to cut a release

- examples/aws/generated/sourcegraph/templates/redis/redis-cache.Deployment.yaml
- examples/aws/generated/sourcegraph/templates/redis/redis-store.Deployment.yaml
- examples/gcp/generated/sourcegraph/templates/redis/redis-cache.Deployment.yaml
- examples/gcp/generated/sourcegraph/templates/redis/redis-store.Deployment.yaml
- examples/manual-storage-class/generated/sourcegraph/templates/redis/redis-cache.Deployment.yaml
- examples/manual-storage-class/generated/sourcegraph/templates/redis/redis-store.Deployment.yaml
- examples/node-selector/generated/sourcegraph/templates/redis/redis-cache.Deployment.yaml
- examples/node-selector/generated/sourcegraph/templates/redis/redis-store.Deployment.yaml
- examples/prometheus/generated/sourcegraph/templates/redis/redis-cache.Deployment.yaml
- examples/prometheus/generated/sourcegraph/templates/redis/redis-store.Deployment.yaml
- examples/with-langs/generated/sourcegraph/templates/redis/redis-cache.Deployment.yaml
- examples/with-langs/generated/sourcegraph/templates/redis/redis-store.Deployment.yaml
- templates/redis/redis-cache.Deployment.yaml
- templates/redis/redis-store.Deployment.yaml
Tested on dogfood.
fixes https://github.com/sourcegraph/sourcegraph/issues/10802
> redis readiness and liveness probe

- docs/scale.md
fix https://github.com/sourcegraph/sourcegraph/issues/11565
> add indexed search scaling guidance

- templates/_helpers.tpl
> remove ADMIN_USERNAMES

- examples/aws/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/gcp/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/manual-storage-class/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/node-selector/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/prometheus/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/with-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- templates/frontend/sourcegraph-frontend.Deployment.yaml
@beyang our old deployment had a liveness probe, did you drop this by accident?
> add liveness probe to frontend

- examples/aws/generated/sourcegraph/templates/indexed-search/indexed-search.Deployment.yaml
- examples/gcp/generated/sourcegraph/templates/indexed-search/indexed-search.Deployment.yaml
- examples/manual-storage-class/generated/sourcegraph/templates/indexed-search/indexed-search.Deployment.yaml
- examples/node-selector/generated/sourcegraph/templates/indexed-search/indexed-search.Deployment.yaml
- examples/prometheus/generated/sourcegraph/templates/indexed-search/indexed-search.Deployment.yaml
- examples/with-langs/generated/sourcegraph/templates/indexed-search/indexed-search.Deployment.yaml
- values.yaml
Includes more information when zoekt-archive-index fails.
Part of https://github.com/sourcegraph/sourcegraph/issues/11571
> indexed-search: Bump zoekt image

- examples/with-exp-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
This fixes the build error: https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/406#f0bc4dca-cd9e-406f-a1fa-452e8cd54d45 - I didn't realize that my branch was behind when I merged.
> regen exp lang server example files

- docs/install.md
- docs/troubleshoot.md
- docs/update.md
Hypothesis: if I get stalled or confused by things, other people might too, so add clarifications to the documentation.
> documentation improvements

- examples/aws/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/aws/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/custom-env-vars/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/custom-env-vars/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/gcp/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/gcp/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/manual-storage-class/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/manual-storage-class/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/node-selector/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/node-selector/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/prometheus/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/prometheus/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/with-exp-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/with-exp-langs/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/with-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/with-langs/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- templates/_helpers.tpl
- test-cases/custom-ls-address/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- test-cases/custom-ls-address/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- test-cases/with-jaeger/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- test-cases/with-jaeger/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
> remove unused SRC_APP_DISABLE_SUPPORT_SERVICES

- examples/aws/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/custom-env-vars/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/gcp/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/manual-storage-class/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/node-selector/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/prometheus/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/with-exp-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/with-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- templates/_helpers.tpl
- test-cases/custom-ls-address/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- test-cases/with-jaeger/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- values.yaml
> remove SRC_SYNTECT_SERVER and rely on default behavior

- examples/aws/generated/sourcegraph/templates/gitserver/gitserver.Deployment.yaml
- examples/aws/generated/sourcegraph/templates/gitserver/gitserver.Service.yaml
- examples/custom-env-vars/generated/sourcegraph/templates/gitserver/gitserver.Deployment.yaml
- examples/custom-env-vars/generated/sourcegraph/templates/gitserver/gitserver.Service.yaml
- examples/gcp/generated/sourcegraph/templates/gitserver/gitserver.Deployment.yaml
- examples/gcp/generated/sourcegraph/templates/gitserver/gitserver.Service.yaml
- examples/manual-storage-class/generated/sourcegraph/templates/gitserver/gitserver.Deployment.yaml
- examples/manual-storage-class/generated/sourcegraph/templates/gitserver/gitserver.Service.yaml
- examples/node-selector/generated/sourcegraph/templates/gitserver/gitserver.Deployment.yaml
- examples/node-selector/generated/sourcegraph/templates/gitserver/gitserver.Service.yaml
- examples/prometheus/generated/sourcegraph/templates/gitserver/gitserver.Deployment.yaml
- examples/prometheus/generated/sourcegraph/templates/gitserver/gitserver.Service.yaml
- examples/with-exp-langs/generated/sourcegraph/templates/gitserver/gitserver.Deployment.yaml
- examples/with-exp-langs/generated/sourcegraph/templates/gitserver/gitserver.Service.yaml
- examples/with-langs/generated/sourcegraph/templates/gitserver/gitserver.Deployment.yaml
- examples/with-langs/generated/sourcegraph/templates/gitserver/gitserver.Service.yaml
- templates/gitserver/gitserver.Deployment.yaml
- templates/gitserver/gitserver.Service.yaml
- test-cases/custom-ls-address/generated/sourcegraph/templates/gitserver/gitserver.Deployment.yaml
- test-cases/custom-ls-address/generated/sourcegraph/templates/gitserver/gitserver.Service.yaml
- test-cases/with-jaeger/generated/sourcegraph/templates/gitserver/gitserver.Deployment.yaml
- test-cases/with-jaeger/generated/sourcegraph/templates/gitserver/gitserver.Service.yaml
> Removed gitserver rpcnew port

- .buildkite/verify-yaml.sh
see https://github.com/garethr/kubeval/issues/93
> better validation

- docs/configure.md
https://github.com/sourcegraph/deploy-sourcegraph/issues/75
> add configure.md section about cpu and memory limits

- renovate.json
helps https://github.com/sourcegraph/deploy-sourcegraph/issues/108
> Renovate group all updates together

- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
see https://github.com/sourcegraph/sourcegraph/issues/458
> don't explicitly set DEPLOY_TYPE=datacenter anymore

- examples/aws/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/aws/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/custom-env-vars/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/custom-env-vars/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/gcp/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/gcp/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/manual-storage-class/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/manual-storage-class/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/node-selector/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/node-selector/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/prometheus/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/prometheus/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/with-exp-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/with-exp-langs/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- examples/with-langs/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- examples/with-langs/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- templates/_helpers.tpl
- test-cases/custom-ls-address/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- test-cases/custom-ls-address/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
- test-cases/with-jaeger/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
- test-cases/with-jaeger/generated/sourcegraph/templates/query-runner/query-runner.Deployment.yaml
see https://github.com/sourcegraph/sourcegraph/issues/458
> helm: don't explicitly set DEPLOY_TYPE=datacenter env var anymore

- base/config-file.ConfigMap.yaml
- docs/configure.md
Fixes https://github.com/sourcegraph/sourcegraph/issues/933
This PR shouldn't be merged until the `3.0-preview` images have been tagged.
> rename appURL -> externalURL

- configure/ingress-nginx/README.md
- docs/sourcegraph-3.0.migrate.md
Fixes https://github.com/sourcegraph/sourcegraph/issues/1815#issuecomment-454104320
> docs: Migration docs for HTTPS / TLS

- docs/configure.md
- docs/troubleshoot.md
Fixes https://github.com/sourcegraph/sourcegraph/issues/1892
> docs: Link to ingress-nginx troubleshooting guide

- base/pgsql/pgsql.Deployment.yaml
Related to https://github.com/sourcegraph/sourcegraph/issues/2192
> base/pgsql: Upgrade image

- base/syntect-server/syntect-server.Deployment.yaml
Adds support for Kotlin and Dart syntax highlighting in code files.
Helps sourcegraph/sourcegraph#2
Helps sourcegraph/sourcegraph#2011
> update syntect_server to include support for Kotlin and Dart syntax highlighting

- renovate.json
Trying to get Renovate to update to release candidate versions.
See https://github.com/renovatebot/config-help/issues/168
> Define unstable pattern

- docs/configure.md
some other random auto formatting happened too
> better configure storage class docs

- base/syntect-server/syntect-server.Deployment.yaml
Fixes https://github.com/sourcegraph/sourcegraph/issues/2615
> Bump syntect_server image

- base/pgsql/pgsql.Deployment.yaml
- base/pgsql/pgsql.Service.yaml
- configure/prometheus/prom-metrics.md
Test Plan: Already deployed to production.
> pgsql: Use latest postgres_exporter

- configure/ingress-nginx/README.md
- configure/ingress-nginx/cloud-generic.yaml
- configure/ingress-nginx/mandatory.yaml
This is already running on sourcegraph.com
> nginx-ingress: update to 0.24.1

- docs/troubleshoot.md
Requested in https://github.com/sourcegraph/sourcegraph/issues/1521
> Adding clarification to under-provisioned issue

- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/indexed-search/indexed-search.Deployment.yaml
- base/management-console/management-console.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- configure/jaeger/jaeger-cassandra.Deployment.yaml
- configure/jaeger/jaeger-collector.Deployment.yaml
- configure/jaeger/jaeger-query.Deployment.yaml
- configure/lang/go/lang-go.Deployment.yaml
- configure/lang/typescript/lang-typescript.Deployment.yaml
- configure/lang/typescript/npm-proxy.Deployment.yaml
- configure/prometheus/alertmanager/alertmanager.Deployment.yaml
- configure/prometheus/prometheus.Deployment.yaml
- configure/ssd/pod-tmp-gc.DaemonSet.yaml
- renovate.json
Fixes https://github.com/sourcegraph/deploy-sourcegraph/issues/263
> use fdqn for sourcegraph docker hub images

- base/indexed-search/indexed-search.Deployment.yaml
See https://github.com/sourcegraph/infrastructure/pull/1602
> Update zoekt docker images to semver tags

- base/indexed-search/indexed-search.Deployment.yaml
see https://github.com/sourcegraph/infrastructure/pull/1618
> Update indexed-search Docker tags

- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/grafana/grafana.Deployment.yaml
this is connected to 
https://github.com/sourcegraph/sourcegraph/pull/5543
this is how this looks like in the k8s deploy context
> frontend grafana dashboards in k8s

- base/grafana/grafana.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
counterpart to 
https://github.com/sourcegraph/sourcegraph/pull/5682
> convert to semver for custom prom/graf docker images

- base/prometheus/prometheus.Deployment.yaml
see https://github.com/sourcegraph/sourcegraph/pull/5855
> prometheus image update (adds user)

- base/indexed-search/indexed-search.Deployment.yaml
- base/indexed-search/indexed-search.Service.yaml
related to
https://github.com/sourcegraph/sourcegraph/issues/5243
depends on 
https://github.com/sourcegraph/zoekt/pull/31
landing first
> declare zoekt web-server as prom target

- base/lsif-server/lsif-server.Deployment.yaml
- docs/configure.md
This updates the postgres config for lsif server after https://github.com/sourcegraph/sourcegraph/pull/5740.
> Note docs about secondary lsif database.

- base/prometheus/prometheus.Deployment.yaml
hooks up alertmanager through service discovery
> prometheus: bump docker image to 10.0.2

- configure/prometheus/alertmanager/README.md
> alertmanager: fix readme

- docs/configure.md
Fixes https://github.com/sourcegraph/sourcegraph/issues/5978
> docs/configure: clarify PostgreSQL version requirements

- base/pgsql/pgsql.ConfigMap.yaml
- base/pgsql/pgsql.Deployment.yaml
This makes it so the `postgresql.conf` file is specified in a ConfigMap, so that the site admin can customize the PostgreSQL config.
> Specify postgresql.conf in ConfigMap

- base/syntect-server/syntect-server.Deployment.yaml
See also https://github.com/sourcegraph/sourcegraph/pull/6843
Fixes sourcegraph/sourcegraph#6827
> update syntect_server to include Starlark (Bazel) support

- base/prometheus/prometheus.Deployment.yaml
contains rules needed for testing high level metrics
> prometheus: image with more highlevel metrics rules

- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-cache.PersistentVolumeClaim.yaml
Translation of https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/73 to deploy-sourcegraph
> redis: Make redis-cache persistent again

- base/syntect-server/syntect-server.Deployment.yaml
Ref. https://github.com/sourcegraph/sourcegraph/pull/8463
> syntect_server: do not fail in environments without IPv6 support

- .buildkite/hooks/pre-command
- .tools-versions
gives us powers over build agent tool versions
> asdf machinery for buildkite tools versions

- base/frontend/sourcegraph-frontend.Role.yaml
- tests/integration/fresh/step1/index.ts
related to https://github.com/sourcegraph/sourcegraph/pull/8805
> frontend: lists services for /-/debug page

- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/lsif-server/lsif-server.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/replacer/replacer.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- configure/lang/go/lang-go.Deployment.yaml
- configure/lang/typescript/lang-typescript.Deployment.yaml
> fix 3.13 to use correct branch

- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/precise-code-intel/api-server.Deployment.yaml
- base/precise-code-intel/api-server.Service.yaml
- base/precise-code-intel/bundle-manager.Deployment.yaml
- base/precise-code-intel/bundle-manager.Service.yaml
- base/precise-code-intel/worker.Deployment.yaml
This mirrors https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/2270.
> Fix bad vars for precise code intel pods.

- kubectl-apply-all.sh
avoids kustomization in apply -f by constructing list of files and passing that as an arg
> avoid kustomize in apply -f by listing all other files

- kubectl-apply-all.sh
left a --dry-run flag by mistake in https://github.com/sourcegraph/deploy-sourcegraph/pull/589
> remove dryrun from previous PR

- kubectl-apply-all.sh
exposed by upstream merge to dot-com
https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/2280
> remove deploy label prefix in apply function

- docs/configure.md
tested with test cluster on GKE (with my github ssh key and one of my private repos)
> docs: ssh mount point for gitserver as non-root

- base/grafana/grafana.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- docs/migrate.md
See inline comments for details.
This change should be cherry-pick'd onto 3.15 before release.
> guarantee Grafana and Prometheus resources

- base/pgsql/pgsql.Deployment.yaml
brings it in line with other deploy contexts
> monitoring: rev up postgres_exporter image version

- .github/workflows/lsif.yml
- docs/configure.md
use upstream release tags and don't follow upstream master
> docs: configure clarifies git flow

- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/replacer/replacer.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
sidecar container jaeger agent docker url
> jaeger agent: fix docker url

- base/precise-code-intel/api-server.Deployment.yaml
- base/precise-code-intel/api-server.Service.yaml
- base/precise-code-intel/bundle-manager.Deployment.yaml
- base/precise-code-intel/bundle-manager.Service.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/precise-code-intel/worker.Service.yaml
- base/prometheus/prometheus.ConfigMap.yaml
Sister [deploy-sourcegraph-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker) change: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/104
> Update precise-code-intel service definitions

- base/grafana/grafana.StatefulSet.yaml
> grafana: update to 3.16.1

- overlays/migrate-to-nonroot/grafana/grafana.StatefulSet.yaml
From https://github.com/aisbaa/deploy-sourcegraph/pull/1
> Aistis grafana migrate to nonroot fix

- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/api-server.Deployment.yaml
- base/precise-code-intel/bundle-manager.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/replacer/replacer.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
> docker images: update to 3.16.2

- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/bundle-manager.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/replacer/replacer.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
> docker images for 3.17

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/bundle-manager.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/replacer/replacer.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
> docker image tags: update to 3.17.3

- base/grafana/grafana.StatefulSet.yaml
> Update grafanan to 3.18.0

- base/grafana/grafana.StatefulSet.yaml
> up grafana to 3.19

- base/grafana/grafana.StatefulSet.yaml
> up grafana to 3.19.1

- base/grafana/grafana.StatefulSet.yaml
> grafana docker image: upgrade to 3.19.2

- .github/workflows/update-tags.yml
- go.mod
- go.sum
- tools/tools.go
> pin update-docker-tags, fix update tags action

- overlays/bases/deployments/kustomization.yaml
- overlays/bases/pvcs/kustomization.yaml
Resources added to `base` have to be added to `overlays/bases/deployments`.
> Add codeintel-db to overlays

- .vscode/extensions.json
> Drop .vscode go extentsion

- overlays/non-root-create-cluster/codeintel-db/codeintel-db.Deployment.yaml
- overlays/non-root-create-cluster/kustomization.yaml
- overlays/non-root/codeintel-db/codeintel-db.Deployment.yaml
- overlays/non-root/kustomization.yaml
fix data dir permissions for the codeintel DB (exactly like for the main DB)
> non-root overlay: fix codeintel DB permissions

- base/minio/minio.Deployment.yaml
Reference doc: https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#container-v1-core
> Added 'minio' bin invoking to args list

- base/minio/minio.Deployment.yaml
- tools/update-docker-tags.sh
I'm going to automate this one day https://github.com/sourcegraph/sourcegraph/issues/15896
> minio: version

- tests/integration/fresh/step1/index.ts
- tests/integration/fresh/step1/package.json
- tests/integration/fresh/step1/yarn.lock
Pulumi appears to have added some bugfixes that we should try to  pickup
> Update pulumi & k8s versions

- tests/integration/fresh/fresh_test.go
> Add 1.18 k8s

- .github/PULL_REQUEST_TEMPLATE.md
- tools/update-docker-tags.sh
This script is too easy to forget to update :( https://github.com/sourcegraph/sourcegraph/issues/15896
> tools: add missing images, update PR template

- tests/integration/restricted/test.sh
> tests: fix condition for cleanup after restricted

- base/prometheus/prometheus.ConfigMap.yaml
for https://github.com/sourcegraph/sourcegraph/issues/17069
> prometheus: set cadvisor metrics name labels

- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
updates redis_exporter to use 64bit binary: related https://github.com/sourcegraph/sourcegraph/issues/11323
> update redis exporter image

- README.md
See https://sourcegraph.slack.com/archives/C07KZF47K/p1612905426350200
All credit goes to @emchap for noticing this!
> README: clarify alternatives to Kubernetes

- base/codeinsights-db/codeinsights-db.Deployment.yaml
Signed-off-by: Stephen Gutekanst <stephen@sourcegraph.com>
> insights: set POSTGRES_PASSWORD

- .github/workflows/lsif.yml
We are seeing a lot of LSIF workflow issues.
> Update lsif.yml workflow to v2 checkout

- base/cadvisor/cadvisor.ClusterRoleBinding.yaml
- base/prometheus/prometheus.ClusterRoleBinding.yaml
- docs/k8s.md
addresses the concerns in https://github.com/sourcegraph/sourcegraph/issues/19077
related docs update https://github.com/sourcegraph/sourcegraph/pull/19171
> update crb, fix dead link

- base/codeintel-db/codeintel-db.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
> Use Postgres 12

- overlays/storageclass/README.md
- overlays/storageclass/kustomization.yaml
- overlays/storageclass/replace-storageclass-name-pvc.yaml
- overlays/storageclass/replace-storageclass-name-sts.yaml
> add overlay to update storageclass

- overlays/minikube/delete-storageclassname.yaml
- overlays/minikube/gitserver-patch.yaml
- overlays/minikube/grafana-patch.yaml
- overlays/minikube/indexed-search-patch.yaml
- overlays/minikube/kustomization.yaml
- overlays/minikube/replace-storageclassname.yaml
changes the storageclass to the default for minikube, rather than deleting it.
> add default sc for minikube

- go.mod
- go.sum
> tools: upgrade sg/images tags

- base/codeintel-db/codeintel-db.Deployment.yaml
Use the Sourcegraph Postgres exporter for the codeintel-db image
> Use Sourcegraph postgres exporter image

- overlays/non-root/codeinsights-db/codeinsights-db.Deployment.yaml
> Update comment for codeinsight db

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.30.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.30.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/22300)
> release: sourcegraph@3.30.0

- base/codeintel-db/codeintel-db.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- overlays/migrate-to-nonprivileged/frontend/sourcegraph-frontend.Deployment.yaml
- overlays/migrate-to-nonprivileged/gitserver/gitserver.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/grafana/grafana.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/indexed-search/indexed-search.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/minio/minio.Deployment.yaml
- overlays/migrate-to-nonprivileged/prometheus/prometheus.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-cache.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-store.Deployment.yaml
- overlays/migrate-to-nonprivileged/searcher/searcher.Deployment.yaml
updates all remaining alpine images to new image name
> change all alpine image to new image name

- base/pgsql/pgsql.Deployment.yaml
related to https://github.com/sourcegraph/sourcegraph/issues/23288
fixes https://github.com/sourcegraph/customer/issues/436 , https://github.com/sourcegraph/customer/issues/433
> rollback postgres

- base/codeinsights-db/codeinsights-db.ConfigMap.yaml
- base/codeintel-db/codeintel-db.ConfigMap.yaml
- base/pgsql/pgsql.ConfigMap.yaml
> Prefer spaces over tabs

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.30.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch changes/release-sourcegraph-3.30.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23326)
> release: sourcegraph@3.30.3

- base/codeinsights-db/codeinsights-db.Deployment.yaml
Found this during documenation work
This affects users who are using manual scripts to parse images
> Remove commented out exporter

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.30.4 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.30.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23996)
> release: sourcegraph@3.30.4

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.31.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.31.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/24515)
> release: sourcegraph@3.31.1

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.31.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.31.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/24737)
> release: sourcegraph@3.31.2

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- tests/integration/fresh/fresh_test.go
This pull request is part of the Sourcegraph 3.32.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.32.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/27764)
> release: sourcegraph@3.32.1

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.33.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.33.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/27855)
> release: sourcegraph@3.33.1

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.34.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.34.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/26714)
> release: sourcegraph@3.34.0

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.33.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.33.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/28044)
> release: sourcegraph@3.33.2

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.34.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.34.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/28104)
> release: sourcegraph@3.34.1

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/query-runner/query-runner.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.34.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.34.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/28640)
> release: sourcegraph@3.34.2

- overlays/low-resource/cadvisor/delete-ClusterRole.yaml
- overlays/low-resource/cadvisor/delete-ClusterRoleBinding.yaml
- overlays/low-resource/cadvisor/delete-Daemonset.yaml
- overlays/low-resource/cadvisor/delete-PodSecurityPolicy.yaml
- overlays/low-resource/cadvisor/delete-ServiceAccount.yaml
- overlays/low-resource/kustomization.yaml
remove cadvisor for use in CI as we don't want to install a daemonset on the CI cluster.
> remove cadvisor for use in CI

- .tool-versions
align with sourcegraph/sourcegraph as per https://github.com/sourcegraph/sourcegraph/pull/29070
> bump k8s tools to align with sourcegraph/sourcegraph

- tests/integration/restricted/install-src.sh
Skipped, this only touches the CI process.
> Check src version before using cached installation

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- tests/integration/restricted/install-src.sh
This pull request is part of the Sourcegraph 3.35.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.35.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/28613)
> release: sourcegraph@3.35.0

- .tool-versions
- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- tests/integration/fresh/step1/.tool-versions
This pull request is part of the Sourcegraph 3.35.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.35.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/29403)
> release: sourcegraph@3.35.1

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.36.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/29290)
> release: sourcegraph@3.36.0

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.36.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30041)
> release: sourcegraph@3.36.1

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.36.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30200)
> release: sourcegraph@3.36.2

- configure/migrator/migrator.Job.yaml
Move Job files to `configure/` so they can be applied later if a customer wants
> Add migrator job spec to configure

- .buildkite/ci-checkov.sh
- .buildkite/hooks/pre-command
- .buildkite/pipeline.yaml
- .tool-versions
- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.36.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30562)
> release: sourcegraph@3.36.3

- .buildkite/hooks/pre-command
- .tool-versions
- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
This pull request is part of the Sourcegraph 3.35.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.35.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30637)
> release: sourcegraph@3.35.2

- .buildkite/ci-checkov.sh
> Enabled checkov skip-checks

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- configure/migrator/migrator.Job.yaml
- overlays/migrate-to-nonprivileged/frontend/sourcegraph-frontend.Deployment.yaml
- overlays/migrate-to-nonprivileged/gitserver/gitserver.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/grafana/grafana.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/indexed-search/indexed-search.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/minio/minio.Deployment.yaml
- overlays/migrate-to-nonprivileged/prometheus/prometheus.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-cache.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-store.Deployment.yaml
- overlays/migrate-to-nonprivileged/searcher/searcher.Deployment.yaml
This pull request is part of the Sourcegraph 3.37.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.37.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30051)
> release: sourcegraph@3.37.0

- base/prometheus/prometheus.ConfigMap.yaml
Part of https://github.com/sourcegraph/customer/issues/679
n/a
> Clarify Prometheus configuration

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- configure/migrator/migrator.Job.yaml
- overlays/migrate-to-nonprivileged/frontend/sourcegraph-frontend.Deployment.yaml
- overlays/migrate-to-nonprivileged/gitserver/gitserver.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/grafana/grafana.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/indexed-search/indexed-search.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/minio/minio.Deployment.yaml
- overlays/migrate-to-nonprivileged/prometheus/prometheus.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-cache.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-store.Deployment.yaml
- overlays/migrate-to-nonprivileged/searcher/searcher.Deployment.yaml
This pull request is part of the Sourcegraph 3.38.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.38.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/33457)
> release: sourcegraph@3.38.1

- .buildkite/verify-label.sh
A file was failing to parse with yj. This was harder than it should of been to track down. This commit improves the verify-label script to run per file so we know which file is responsible.
Other improvements:
- Check if the value is sourcegraph, not containing sourcegraph. Uses jq equality check.
- Don't install yj if already present. Useful for testing locally.
- Use bash on env. bash at /bin can be old (and doesn't exist on NixOS).
Test Plan: modified some yaml files to fail the rule and ran .buildkite/verify-label.sh.
> ci: output which file is failing verify-labels

- .buildkite/hooks/pre-command
fixes a cosmetic error in an echo statement
a green run on this PR
> fix dir in echo

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- configure/migrator/migrator.Job.yaml
- overlays/migrate-to-nonprivileged/frontend/sourcegraph-frontend.Deployment.yaml
- overlays/migrate-to-nonprivileged/gitserver/gitserver.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/grafana/grafana.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/indexed-search/indexed-search.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/minio/minio.Deployment.yaml
- overlays/migrate-to-nonprivileged/prometheus/prometheus.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-cache.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-store.Deployment.yaml
- overlays/migrate-to-nonprivileged/searcher/searcher.Deployment.yaml
This pull request is part of the Sourcegraph 3.39.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.39.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/34545)
> release: sourcegraph@3.39.1

- .github/workflows/pr-auditor.yml
- .tool-versions
> Upgrade golang version

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- configure/migrator/migrator.Job.yaml
- overlays/migrate-to-nonprivileged/frontend/sourcegraph-frontend.Deployment.yaml
- overlays/migrate-to-nonprivileged/gitserver/gitserver.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/grafana/grafana.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/indexed-search/indexed-search.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/minio/minio.Deployment.yaml
- overlays/migrate-to-nonprivileged/prometheus/prometheus.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-cache.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-store.Deployment.yaml
- overlays/migrate-to-nonprivileged/searcher/searcher.Deployment.yaml
This pull request is part of the Sourcegraph 3.40.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.40.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/36790)
> release: sourcegraph@3.40.2

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- configure/migrator/migrator.Job.yaml
- overlays/migrate-to-nonprivileged/frontend/sourcegraph-frontend.Deployment.yaml
- overlays/migrate-to-nonprivileged/gitserver/gitserver.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/grafana/grafana.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/indexed-search/indexed-search.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/minio/minio.Deployment.yaml
- overlays/migrate-to-nonprivileged/prometheus/prometheus.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-cache.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-store.Deployment.yaml
- overlays/migrate-to-nonprivileged/searcher/searcher.Deployment.yaml
This pull request is part of the Sourcegraph 3.41.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.41.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/38644)
> release: sourcegraph@3.41.1

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- configure/migrator/migrator.Job.yaml
- overlays/migrate-to-nonprivileged/frontend/sourcegraph-frontend.Deployment.yaml
- overlays/migrate-to-nonprivileged/gitserver/gitserver.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/grafana/grafana.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/indexed-search/indexed-search.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/minio/minio.Deployment.yaml
- overlays/migrate-to-nonprivileged/prometheus/prometheus.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-cache.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-store.Deployment.yaml
- overlays/migrate-to-nonprivileged/searcher/searcher.Deployment.yaml
This pull request is part of the Sourcegraph 3.42.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.42.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/38119)
> release: sourcegraph@3.42.0

- overlays/non-privileged/README.md
Additionally added a link to the overlay.
Test Plan: n/a
> non-privileged: correct name for create overlay in docs

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- configure/migrator/migrator.Job.yaml
- overlays/migrate-to-nonprivileged/frontend/sourcegraph-frontend.Deployment.yaml
- overlays/migrate-to-nonprivileged/gitserver/gitserver.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/grafana/grafana.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/indexed-search/indexed-search.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/minio/minio.Deployment.yaml
- overlays/migrate-to-nonprivileged/prometheus/prometheus.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-cache.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-store.Deployment.yaml
- overlays/migrate-to-nonprivileged/searcher/searcher.Deployment.yaml
This pull request is part of the Sourcegraph 3.42.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.42.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/39596)
> release: sourcegraph@3.42.1

- .buildkite/verify-yaml.sh
revert https://github.com/sourcegraph/deploy-sourcegraph/pull/986/files
CI
> Fix target cluster

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/minio/minio.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- configure/migrator/migrator.Job.yaml
- overlays/migrate-to-nonprivileged/frontend/sourcegraph-frontend.Deployment.yaml
- overlays/migrate-to-nonprivileged/gitserver/gitserver.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/grafana/grafana.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/indexed-search/indexed-search.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/minio/minio.Deployment.yaml
- overlays/migrate-to-nonprivileged/prometheus/prometheus.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-cache.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-store.Deployment.yaml
- overlays/migrate-to-nonprivileged/searcher/searcher.Deployment.yaml
This pull request is part of the Sourcegraph 3.43.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.43.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/39333)
> release: sourcegraph@3.43.0

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/jaeger/jaeger.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- tests/integration/restricted/test.sh
Manual image updates, as requested by @keegancsmith 
Should pass CI
> all: update images to latest insiders tag

- base/otel-collector/otel-collector.ConfigMap.yaml
Minor tweaks to align with the template configuration in https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/848 and move configuration that a user might change to the top
n/a
> otel-collector: update template config

- overlays/low-resource/otel-agent-patch.yaml
Set safe to evict to true to ensure that the node can be scaled down
Only changing eviction policy. See if Sourcegraph QA integration test performs 👌🏼
> otel-agent(low resource): set safe to evict for otel-agent

- .tool-versions
Bumping to go 1.19.3 to match src/src
N/A
> go version 1.19.3

- .tool-versions
Merging go 1.19.3 into the release branch
N/A
> go version 1.19.3 (#4202)

- base/otel-collector/otel-agent.ConfigMap.yaml
switch port to end point for otel-agent config
CI + tested locally
> otel:fix port/endpoint

- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- configure/migrator/migrator.Job.yaml
- overlays/jaeger/jaeger.Deployment.yaml
- overlays/migrate-to-nonprivileged/blobstore/blobstore.Deployment.yaml
- overlays/migrate-to-nonprivileged/gitserver/gitserver.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/grafana/grafana.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/indexed-search/indexed-search.StatefulSet.yaml
- overlays/migrate-to-nonprivileged/prometheus/prometheus.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-cache.Deployment.yaml
- overlays/migrate-to-nonprivileged/redis/redis-store.Deployment.yaml
- overlays/migrate-to-nonprivileged/searcher/searcher.Deployment.yaml
This pull request is part of the Sourcegraph 4.2.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.2.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/45373)
> release: sourcegraph@4.2.1

- overlays/bases/deployments/kustomization.yaml
Verified locally using the different overlays.
> add workers-executors.Service.yaml file to overlays base

- go.mod
- go.sum
> mod: update image list

- .buildkite/integration-restricted-test.sh
- base/blobstore/blobstore.Deployment.yaml
- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/github-proxy/github-proxy.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/node-exporter/node-exporter.DaemonSet.yaml
- base/otel-collector/otel-agent.DaemonSet.yaml
- base/otel-collector/otel-collector.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- configure/embeddings/embeddings.ConfigMap.yaml
- configure/embeddings/embeddings.Deployment.yaml
- configure/embeddings/embeddings.Service.yaml
- tests/integration/restricted/nonroot-policy.yaml
Adds Embeddings service to handle Cody embeddings
- Not included in the base install, can be optionally enabled
- Uses a configmap for upload backend configuration (optional on worker so it doesn't block if configmap doesn't exist)
- Generated a cluster and applied both the cluster and the embeddings config
- Successfully generated embeddings in SG blobstore and GCS
> Embeddings Service

- base/worker/worker.Deployment.yaml
- configure/embeddings/embeddings.Deployment.yaml
- configure/embeddings/embeddings.Service.yaml
- configure/embeddings/emebeddings.ConfigMap.yaml
Backports Embeddings service from https://github.com/sourcegraph/deploy-sourcegraph/pull/4245
See PR above
> Add Embeddings service

- base/blobstore/blobstore.Deployment.yaml
- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/node-exporter/node-exporter.DaemonSet.yaml
- base/otel-collector/otel-agent.DaemonSet.yaml
- base/otel-collector/otel-collector.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- overlays/jaeger/jaeger.Deployment.yaml
> Release update image tags

- base/blobstore/blobstore.Deployment.yaml
- base/cadvisor/cadvisor.DaemonSet.yaml
- base/codeinsights-db/codeinsights-db.Deployment.yaml
- base/codeintel-db/codeintel-db.Deployment.yaml
- base/frontend/sourcegraph-frontend.Deployment.yaml
- base/gitserver/gitserver.StatefulSet.yaml
- base/grafana/grafana.StatefulSet.yaml
- base/indexed-search/indexed-search.StatefulSet.yaml
- base/node-exporter/node-exporter.DaemonSet.yaml
- base/otel-collector/otel-agent.DaemonSet.yaml
- base/otel-collector/otel-collector.Deployment.yaml
- base/pgsql/pgsql.Deployment.yaml
- base/precise-code-intel/worker.Deployment.yaml
- base/prometheus/prometheus.Deployment.yaml
- base/redis/redis-cache.Deployment.yaml
- base/redis/redis-store.Deployment.yaml
- base/repo-updater/repo-updater.Deployment.yaml
- base/searcher/searcher.Deployment.yaml
- base/symbols/symbols.Deployment.yaml
- base/syntect-server/syntect-server.Deployment.yaml
- base/worker/worker.Deployment.yaml
- overlays/jaeger/jaeger.Deployment.yaml
> update to 5.8.1579

- .github/workflows/backport.yml
Standardizing across deployment repos
> NOTE:
N/A
> feat/ci: Add backport automation
